### PR TITLE
service-now: add posibility to run tests in parallel on different browsers

### PR DESCRIPTION
**Pull request by mmelko**
//test: `@servicenow`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - ServiceNow-amq/log | Get incident from service now 
Integration - ServiceNow-amq/log | Create incident from syndesis integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmelko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Validate all credentials 
Integration - ServiceNow-amq/log | Get incident from service now 
Integration - ServiceNow-amq/log | Create incident from syndesis integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmelko** [comment]
yeah, but in next daily build it should be back

**Comment by mmelko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
