### PR TITLE
[FIX] FTP to FTP test fix

### PR DESCRIPTION
**Pull request by Stefan365**
//test: `@ftp-download-ftp-upload`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
Integration - FTP to FTP | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by Stefan365** [comment]
on local "@smoke or @ftp-download-ftp-upload" passed

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
