### PR TITLE
[Kafka] Add missing parameter

### PR DESCRIPTION
**Pull request by avano**
//test: `@kafka`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
