### PR TITLE
fix: google sheet stale elements fix

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@google-sheets`

### CODE REVIEW

**Comment by avano** [comment]
@mmuzikar 

```
1 commit
Merge pull request #1097 from mmelko/master
pure-bot authored and mmuzikar committed yesterday
```

:thinking:

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | create spreadsheet 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
Something fishy's going on with the gsheets connector that needs more investigation, from our side tests are no longer failing because of stale elements.

**Comment by asmigala** [comment]
So should this be merged?

**Comment by mmuzikar** [comment]
@asmigala yup it is ready to merge

**Pull request merged**
