### PR TITLE
[relates #194] Depiction of elements. part 1

### PR DESCRIPTION
**Pull request by Stefan365**
elements picture, part 1.
TBD: 
integrations/datamapper
connections/edit+list

### CODE REVIEW

**Comment by Stefan365** [comment]
@dsimansk done.

**Comment by dsimansk** [comment]
I've noticed that image `docs/snapshots/integrations/detail/IN.d.0_h1_L1.png` isn't cut properly and there's your second desktop :)

**Comment by Stefan365** [comment]
@dsimansk fortunately, nothing compromising was there... :-) 
done.

**Comment by dsimansk** [comment]
@Stefan365 is it good to go now?

**Comment by Stefan365** [comment]
@dsimansk I think so

**Pull request merged**
