### PR TITLE
[FUSEQE-2893] Fix UI tests after UI changes

### PR DESCRIPTION
**Pull request by avano**
//test: `@integrations-ftp-to-ftp,@integrations-gmail,@slack,@integrations-twitter-to-db,@3scale`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Pull request merged**
