### PR TITLE
updated information about running syndesis tests with chrome

### PR DESCRIPTION
**Pull request by jsafarik**
//skip-ci

### CODE REVIEW

**Comment by avano** [comment]
@jsafarik or `mvn install` as the plugin is bound to install phase: https://github.com/syndesisio/syndesis-qe/blob/5ede613eeabf6fdb1df70f76e766d5c8ae5cff75/ui-tests/pom.xml#L66-L75

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by jsafarik** [comment]
@avano well, yes, but I guess that just for the purpose of installing new drivers, executing the plugin itself is faster, isn't it?

**Pull request merged**
