### PR TITLE
[data_mapper] remove open data mapper collection mappings where not p…

### PR DESCRIPTION
**Pull request by tplevko**
…ossible

//test: `@api-provider-post-collection or @integrations-datashapes-input-change or @email-receive or  @email-receive-folder or @gmail-receive or @integration-import-export-classic-input or @integrations-odata-create or @gh-5060`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData Connector | Create entity in OData service 
OData Connector | Read enum mapping from OData service tests 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData Connector | Create entity in OData service 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | API Provider POST collection 
Integration - DB to DB | Read and update operations 
Email connector | Receive Email with SSL 
Email connector | Receive Email with SSL 
Email connector | Receive an e-mail from specific folder 
Google mail Connector | Receive an e-mail 
Integration - Import Export | Import and export classic-input 
OData Connector | Create entity in OData service 
OData Connector | Read enum mapping from OData service tests 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | API Provider POST collection 
Integration - DB to DB | Read and update operations 
Email connector | Receive Email with SSL 
Email connector | Receive Email with SSL 
Email connector | Receive an e-mail from specific folder 
Google mail Connector | Receive an e-mail 
Integration - Import Export | Import and export classic-input 
OData Connector | Create entity in OData service 
OData Connector | Read enum mapping from OData service tests 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
merging because this was already approved

**Pull request merged**
