### PR TITLE
[3scale] Add changes required for 3scale service discovery testing

### PR DESCRIPTION
**Pull request by jsafarik**
//test: `@3scale-annotations`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-common/src/main/java/io/syndesis/qe/steps/
  CommonSteps.java:48:8: Unused import - org.apache.commons.lang3.StringUtils. [UnusedImports]
utilities/src/main/java/io/syndesis/qe/utils/
  TestUtils.java:231: 'block rcurly' has incorrect indentation level 20, expected level should be one of the following: 16, 24. [Indentation]
```

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-common/src/main/java/io/syndesis/qe/steps/
  CommonSteps.java:48:8: Unused import - org.apache.commons.lang3.StringUtils. [UnusedImports]
utilities/src/main/java/io/syndesis/qe/utils/
  TestUtils.java:231: 'block rcurly' has incorrect indentation level 20, expected level should be one of the following: 16, 24. [Indentation]
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
3scale integration | 3scale discovery annotations 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by avano — APPROVED** [review]

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
