### PR TITLE
Update AMQ Streams from 1.4.0 to 1.7.0 + DM fix for undefined datatype

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
@mkralik3 we were requested previously to test against latest amq-streams (productized images) and not against community images

**Comment by mkralik3** [comment]
@avano  roger that. I am going to rework it.

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by avano — APPROVED** [review]

**Pull request merged**
