### PR TITLE
Fix @create delete api connector

### PR DESCRIPTION
**Pull request by mastepan**
//test: `@create-delete-api-connector`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by asmigala** [comment]
Please rebase

**Comment by mastepan** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
