### PR TITLE
Improve tests stability

### PR DESCRIPTION
**Pull request by mkralik3**
* SFTP
* google calendar
* template
* fix regex for operator name (due to dc to deployment change)
* add extension jar to operator package

//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by avano — APPROVED** [review]

**Pull request merged**
