### PR TITLE
Use bonigarcia/webdrivermanager for automatically detection of webdrivers

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mmuzikar** [comment]
@mkralik3 can you run smoke UI tests to make sure it won't fail on Jenkins?

**Comment by mkralik3** [comment]
@mmuzikar  I had already run it from my branch before I moved this from draft. 
https://fuse-7x-jenkins-csb-fuse-qe.apps.ocp4.prod.psi.redhat.com/job/fuse-7.9-syndesis-tests-chrome/307/
https://fuse-7x-jenkins-csb-fuse-qe.apps.ocp4.prod.psi.redhat.com/job/fuse-7.9-syndesis-tests-firefox/313/

**Review by mmuzikar — APPROVED** [review]
Cool LGTM then

**Pull request merged**
