### PR TITLE
integration status feature migration

### PR DESCRIPTION
**Pull request by jsafarik**
//test: `@integrations-check-starting-status`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/
  IntegrationsList.java:13:8: Unused import - io.syndesis.qe.pages.integrations.editor.add.connection.ChooseAction. [UnusedImports]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on detail page 
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on detail page 
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on detail page 
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on detail page 
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on detail page 
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by asmigala** [comment]
Is this ready for review?

**Comment by jsafarik** [comment]
@asmigala yes, should've added the label to this PR.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
