### PR TITLE
[FIX] Kudu test fix test

### PR DESCRIPTION
**Pull request by Stefan365**
//test: `@integrations-kudu-insert`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by Stefan365** [comment]
Tests failed on known issue ENTESB-11787

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Kudu connector | Insert data into kudu table 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
