### PR TITLE
odata connector smoke and reproducer tests

### PR DESCRIPTION
**Pull request by jsafarik**
//test: `@odata`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:6: Wrong order for 'io.syndesis.qe.accounts.Account' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:11: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:13: Wrong order for 'org.json.JSONObject' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:13:8: Unused import - org.json.JSONObject. [UnusedImports]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:19: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/
  TestSuiteParent.java:4: 'org.junit.AfterClass' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/
  TestSuiteParent.java:10: Wrong order for 'io.syndesis.qe.bdd.CommonSteps' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/
  TestSuiteParent.java:15: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/
  TestSuiteParent.java:41: 'lambda arguments' has incorrect indentation level 16, expected level should be 12. [Indentation]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:11: Wrong order for 'io.syndesis.qe.templates.AmqTemplate' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:22: Wrong order for 'io.syndesis.qe.templates.WildFlyTemplate' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:23: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:108: @And should not be used. [RegexpSingleline]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:3:8: Unused import - io.fabric8.kubernetes.api.model.KubernetesList. [UnusedImports]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:4: Wrong order for 'io.syndesis.qe.utils.OpenShiftUtils' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:7: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:8: Wrong order for 'io.fabric8.openshift.api.model.Template' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:10: Wrong order for 'java.io.IOException' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:69:47: '{' is not preceded with whitespace. [WhitespaceAround]
utilities/src/main/java/io/syndesis/qe/utils/
  ODataUtils.java:5: Wrong order for 'java.io.IOException' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/utils/
  ODataUtils.java:9: Wrong order for 'org.assertj.core.api.Assertions.fail' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/utils/
  ODataUtils.java:24:52: '{' is not preceded with whitespace. [WhitespaceAround]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:6: Wrong order for 'io.syndesis.qe.accounts.Account' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:11: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:13: Wrong order for 'org.json.JSONObject' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:13:8: Unused import - org.json.JSONObject. [UnusedImports]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:19: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/
  TestSuiteParent.java:4: 'org.junit.AfterClass' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/
  TestSuiteParent.java:10: Wrong order for 'io.syndesis.qe.bdd.CommonSteps' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/
  TestSuiteParent.java:15: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:11: Wrong order for 'io.syndesis.qe.templates.AmqTemplate' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:22: Wrong order for 'io.syndesis.qe.templates.WildFlyTemplate' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:23: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  OpenshiftValidationSteps.java:108: @And should not be used. [RegexpSingleline]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:3:8: Unused import - io.fabric8.kubernetes.api.model.KubernetesList. [UnusedImports]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:4: Wrong order for 'io.syndesis.qe.utils.OpenShiftUtils' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:7: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:8: Wrong order for 'io.fabric8.openshift.api.model.Template' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:10: Wrong order for 'java.io.IOException' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/templates/
  WildFlyTemplate.java:69:47: '{' is not preceded with whitespace. [WhitespaceAround]
utilities/src/main/java/io/syndesis/qe/utils/
  ODataUtils.java:5: Wrong order for 'java.io.IOException' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/utils/
  ODataUtils.java:9: Wrong order for 'org.assertj.core.api.Assertions.fail' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/utils/
  ODataUtils.java:24:52: '{' is not preceded with whitespace. [WhitespaceAround]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:5: 'io.cucumber.datatable.DataTable' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:6: Wrong order for 'io.syndesis.qe.utils.HTTPResponse' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:9: 'cucumber.api.java.en.Then' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:14: Wrong order for 'java.util.HashMap' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  ODataSteps.java:18: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
