### PR TITLE
[FUSEQE-6269] Fixed Slack scenarios

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@slack and not(@disabled)`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Slack Connector | Check that slack received a message from an integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Import Export | Import from different syndesis instance 
Slack Connector | Check that slack received a message from an integration 
Slack Connector | Check Maximum Messages to Retrieve and Delay function in SLACK consumer 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Slack Connector | Check that slack received a message from an integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
@tplevko can you merge this ? the one test failed due to the issue with query in the DB step

**Comment by tplevko** [comment]
@mkralik3 can you annotate the failing test with the ENTESB-11787 annotation?

**Comment by mkralik3** [comment]
Yes I can. Should I annotate all other tests which are using "Periodic SQL Invocation"?

**Pull request merged**
