### PR TITLE
validate credentials from @smoke removed

### PR DESCRIPTION
**Pull request by AnetaCadova**
//test: `@smoke`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@AnetaCadova please change the commit message to `[FUSEQE-zxc] Remove validate...`, I'll talk about it in the next meeting

Also if you want to run some test tags, you need to enclose the tags in \`backticks\`

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
