### PR TITLE
[FUSEQE-4310] remove import-export_backup tests

### PR DESCRIPTION
**Pull request by wyvie**
also cleanup import-export tests a bit and add checks for encrypted exported fields

//test: `@integration-import-export-classic-input`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - Import Export | Import and export classic-input 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Import Export | Import and export classic-input 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request closed without merging**
