### PR TITLE
Fix OData connection

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@odata or @odata-server-certificate`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData Connector | Read entity w complex param from OData service tests 
```

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by jsafarik — APPROVED** [review]

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
