### PR TITLE
fix Name fill before publishing an integration

### PR DESCRIPTION
**Pull request by mastepan**

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/
  CreateIntegration.java:10: Wrong order for 'io.syndesis.qe.pages.SyndesisPageObject' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/
  CreateIntegration.java:11: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mastepan** [comment]
@avano can you please merge this one? Multiple tests fail/have being blocked by this.

**Comment by avano** [comment]
@mastepan please fix the checkstyle and we can merge

**Comment by mastepan** [comment]
nooo :/  I didn't break it...  @avano Please merge and I'll fix that later today. I don't know the right order of the imports. Other people are being blocked by this.

**Comment by avano** [comment]
just apply this patch:

```
From fd7c3fefa4ae6b38cce60a1cc5b9cce01503958f Mon Sep 17 00:00:00 2001
From: Andrej Vano <avano@redhat.com>
Date: Wed, 16 Oct 2019 15:46:10 +0200
Subject: [PATCH] [Checkstyle] Fix checkstyle

---
 .../qe/pages/integrations/editor/CreateIntegration.java        | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java b/ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java
index cbff041b..0012be89 100644
--- a/ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java
+++ b/ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java
@@ -3,11 +3,12 @@ package io.syndesis.qe.pages.integrations.editor;
 import static com.codeborne.selenide.Condition.visible;
 import static com.codeborne.selenide.Selenide.$;
 
+import io.syndesis.qe.pages.SyndesisPageObject;
+
 import org.openqa.selenium.By;
 
 import com.codeborne.selenide.SelenideElement;
 
-import io.syndesis.qe.pages.SyndesisPageObject;
 import lombok.extern.slf4j.Slf4j;
 
 @Slf4j
-- 
2.23.0


```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
