### PR TITLE
[ui] fixed some failing api provider issues

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@api-provider`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | Create API provider from url spec todo-app 
API Provider Integration | Create API provider from file spec swagger/connectors/todo.json 
API Provider Integration | Create API provider from file spec swagger/connectors/todo.swagger.yaml 
API Provider Integration | Create from scratch 
API Provider Integration | API Provider GET single 
API Provider Integration | API Provider GET non-existent 
API Provider Integration | API Provider GET collection 
API Provider Integration | API Provider GET emptycollection 
API Provider Integration | API Provider POST new 
API Provider Integration | API Provider POST existing  - known issue
API Provider Integration | API Provider POST collection 
API Provider Integration | API Provider PUT 
API Provider Integration | API Provider DELETE  - known issue
API Provider Integration | API Provider export roundtrip 
API Provider Integration | API Provider Edit OpenAPI - add operation 
API Provider Integration | API Provider Edit OpenAPI - edit unimplemented operation 
API Provider Integration | API Provider Edit OpenAPI - edit implemented operation 
API Provider Integration | API Provider Edit OpenAPI - delete implemented operation 
API Provider Integration | API Provider Edit OpenAPI - delete unimplemented operation 
API Provider Integration | Publishing an integration with all operations deleted should not be possible 
API Provider Integration | Clicking Go To Operation List does not discard progress in API Provider 
API Provider Integration | API Provider operation with simple return type 
API Provider Integration | API Provider start and stop connection cannot be deleted 
API Provider Integration | Base path in API Provider URL 
API Provider Integration | Conditional flows used in API Provider 
API Provider Integration | Check that API Provider shows the number of flow instead of steps for random flow 
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
Fixes I provided were for: API Provider POST existing, API Provider POST collection and API Provider Edit OpenAPI - edit implemented operation
Tests results:
```
[ERROR] Tests run: 29, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 4,184.324 s <<< FAILURE! - in io.syndesis.qe.CucumberTest
[ERROR] Create from scratch(API Provider Integration)  Time elapsed: 291.18 s  <<< FAILURE!
org.assertj.core.api.SoftAssertionError: 

The following assertion failed:
1) expected:<[200]> but was:<[503]>
at ApiProviderSteps.checkResponse(ApiProviderSteps.java:168) expected:<[200]> but was:<[503]>


[ERROR] API Provider DELETE(API Provider Integration)  Time elapsed: 176.513 s  <<< FAILURE!
org.assertj.core.api.SoftAssertionError: 

The following assertion failed:
1) expected:<""> but was:<null>
at ApiProviderSteps.checkResponse(ApiProviderSteps.java:170) expected:<""> but was:<null>


[ERROR] API Provider export roundtrip(API Provider Integration)  Time elapsed: 278.465 s  <<< FAILURE!
org.assertj.core.api.SoftAssertionError: 

The following 2 assertions failed:
1) expected:<[200]> but was:<[503]>
at ApiProviderSteps.checkResponse(ApiProviderSteps.java:168) expected:<[200]> but was:<[503]>
2) expected:<"[{"id":1}]"> but was:<"[]">
at ApiProviderSteps.checkResponse(ApiProviderSteps.java:170) expected:<"[{"id":1}]"> but was:<"[]">

```

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | API Provider DELETE  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
