### PR TITLE
[ui][fix][FUSEQE-3282] make scenario names unique

### PR DESCRIPTION
**Pull request by mcada**
//skip-ci

### CODE REVIEW

**Comment by avano** [comment]
@mcada if it is related to some JIRA, use it in the commit message, e.g. `[FUSEQE-12345] Commit msg`

**Comment by mcada** [comment]
@avano good point, I wasn't used to do that, I only mention PR in JIRA

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
