### PR TITLE
[FUSEQE-8553] Add more disconnected install scenarios

### PR DESCRIPTION
**Pull request by avano**
//test: `@disconnected-install and not @camel-k`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Disconnected install | Camel-K 
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Conditional flows - content base routing | Conditional flows - functional test 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Disconnected install | Camel-K 
Integration - Database | Smoke - Periodic invocation to Insert 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
