### PR TITLE
[FUSEQE-10188] - fix Kafka tests

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci

Removed code for creating/deleting ClusterRole. It is not needed anymore. https://issues.redhat.com/browse/ENTESB-14507

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | from database to kafka topic 
Integration - DB to DB | from database to kafka topic 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
I found a problem with why autodiscovery doesn't work on PR job. It looks that ClusterRoleBinding with namespace is not updated when it is already on OCP. Which is strange because locally it works. I am investigating it.

**Comment by mkralik3** [comment]
Reopen https://issues.redhat.com/browse/ENTESB-14507 due to https://github.com/syndesisio/syndesis/pull/9052/commits/f7cd153d495bd2a7e1f189786f4438c46b513aab

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@avano 
The tests failed due to issue: https://issues.redhat.com/browse/ENTESB-14780
WIth `--cluser` flag, the test works https://online-jenkins-csb-fuse-qe.cloud.paas.psi.redhat.com/view/7.8/job/fuse-7.8-syndesis-tests-firefox/12/

**Review by avano — APPROVED** [review]

**Comment by avano** [comment]
:crossed_fingers: :grin:

**Pull request merged**
