### PR TITLE
Added E2E test for CSV and CRUD test for CSV dialog

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by mmuzikar — APPROVED** [review]
LGTM :fire:

**Pull request merged**
