### PR TITLE
Add wait for operations to fully load (due to OCP 4.1. failures)

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@api-provider-create-from-spec`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
