### PR TITLE
[ui][fix] SF refactoring (FUSEQE-1639) removing SF from @data-buckets…

### PR DESCRIPTION
**Pull request by mmajerni**
… and @twitter-to-db integrations

Signed-off-by: mmajerni <mmajerni@redhat.com>

//test: @data-buckets-usage,@integrations-twitter-to-db

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmajerni** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
