### PR TITLE
[Operator] Undeploy syndesis before cleaning namespace

### PR DESCRIPTION
**Pull request by avano**
the xtf bump should resolve issue from @asmigala that sometimes the waitForSyndesis ends too soon

//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by zregvart** [comment]
The intent is that the `OAuthClient` is removed when the Syndesis custom resource is removed, perhaps deleting it first and then the namespace would help? If that doesn't work then we're looking at a bug in the `syndesis-operator`.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@zregvart 

currently we were deleting only selected resources https://github.com/xtf-cz/xtf/blob/utilities-0.6/src/main/java/cz/xtf/openshift/OpenShiftUtil.java#L822-L839 .

You are right, when I delete the custom resource, everything works as supposed. but since we want to clean the namespace is imho better to drop-create. 

wdyt? 

btw did I tickle your OAuth spidey-senses? :dancer:

**Comment by zregvart** [comment]
> You are right, when I delete the custom resource, everything works as supposed. but since we want to clean the namespace is imho better to drop-create.
> 
> wdyt?

With using the operator we're also kinda testing that operator cleans up after itself. I'd like to move to a fully CR/operator driven thing for everything and make that as good experience as it can be. With all the shell/code we have outside of it we're just increasing our fragility. (2c) 

> btw did I tickle your OAuth spidey-senses? dancer

:spider: 

I'm kinda subscribed to everything and try to keep up, call me crazy...

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
