### PR TITLE
[ui] stability fixes

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@api-client-auth-api-key-headers or @api-client-auth-api-key-query or @openapi-client`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  DbValidationSteps.java:6:8: Unused import - io.syndesis.qe.test.InfraFail. [UnusedImports]
utilities/src/main/java/io/syndesis/qe/bdd/validation/
  DbValidationSteps.java:145:24: '{' is not preceded with whitespace. [WhitespaceAround]
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | API key used in API client provided in headers 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | API key used in API client provided in query 
```

**Comment by mmuzikar** [comment]
retest this please

**Comment by mmuzikar** [comment]
retest this please

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  DataMapper.java:17:8: Unused import - io.syndesis.qe.utils.Conditions. [UnusedImports]
```

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@mmuzikar please, backport changes also to the master

**Pull request merged**
