### PR TITLE
[ui][fix]migration of apicurio.feature

### PR DESCRIPTION
**Pull request by mmajerni**
//test: `@apicurio`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:26: Wrong order for 'io.syndesis.qe.utils.TestUtils' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:28: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:252:40: String literal expressions should be on the left side of an equalsIgnoreCase comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:257:40: String literal expressions should be on the left side of an equalsIgnoreCase comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:300:25: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:302:32: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:6: 'cucumber.api.java.en.Then' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:8: Wrong order for 'io.syndesis.qe.utils.TestUtils' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:10: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:11: Wrong order for 'org.openqa.selenium.By' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:15: Wrong order for 'com.codeborne.selenide.CollectionCondition.sizeGreaterThanOrEqual' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:16: Using the '.*' form of import should be avoided - com.codeborne.selenide.Condition.*. [AvoidStarImport]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:17: Using the '.*' form of import should be avoided - com.codeborne.selenide.Selenide.*. [AvoidStarImport]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:18: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
@mmajerni please rebase to master and fix checkstyle, we need this merged asap

**Comment by asmigala** [comment]
merged in #1018, closing

**Pull request closed without merging**
