### PR TITLE
[Dynamo-DB] Add update test for Dynamo DB - ENTESB-11740

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@dynamodb`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
@tplevko if you have a jira, please use `[JIRA-123]` at the start of your commit msg

**Pull request merged**
