### PR TITLE
[ui][fix] fix slack tests

### PR DESCRIPTION
**Pull request by mcada**
//test: `@integrations-slack`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@mcada there seems to be the a "fix data buckets" commit present in this PR

**Comment by mcada** [comment]
@tplevko thanks, my bad :)

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
