### PR TITLE
[ui-tests] Form filling - new Form.fillBy methods

### PR DESCRIPTION
**Pull request by mastepan**
* used e.g. in connections.feature

### CODE REVIEW

**Comment by mcada** [comment]
Changes we talked about today are already in, overall it looks ok. I vote for making fill methods static with root element as parameter as instances are not necessary and don't hold any data, but that is probably for another conversation. Martin said that we are now waiting for @dsimansk to merge so David feel free to merge this when you are ready.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by dsimansk** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by dsimansk** [comment]
@mastepan @mcada the `@smoke` test is failing with this PR. Could one of you address this?

**Comment by dsimansk** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
