### PR TITLE
fix @integration-check-starting-status-on-detail-page

### PR DESCRIPTION
**Pull request by mastepan**
//test: `@integrations-check-starting-status`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mcada** [comment]
retest this please

**Comment by mcada** [comment]
@mastepan 
When you are writing algorithms on like 100 rows, please consider using helper methods. Your algorithm could look something like this:

```
for...{
if(shouldWeBreak()) break;
status = getStartingStatus();
compareStatus(status, lastStatus);
verifyStatusIndex(status);
sleep 200ms
}
```
Then you can tell on the first look what it does... Yours is not pretty nor readable, some parts are not required, but should work. Also next time please start all scenarios which are affected by changed code, if possible.

@avano do we leave it like it is or should it be refactored?

**Comment by mastepan** [comment]
> @mastepan
> When you are writing algorithms on like 100 rows, please consider using helper methods. Your algorithm could look something like this:
> 
> ```
> for...{
> if(shouldWeBreak()) break;
> status = getStartingStatus();
> compareStatus(status, lastStatus);
> verifyStatusIndex(status);
> sleep 200ms
> }
> ```
> Then you can tell on the first look what it does... Yours is not pretty nor readable, some parts are not required, but should work. Also next time please start all scenarios which are affected by changed code, if possible.
> 
> @avano do we leave it like it is or should it be refactored?

Agree but It's not a priority right now. If you want it to be refactored, I'll put it in my backlog. This is just fix of something that already exists.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
@mastepan your scenario is not stable, also this algorithm refactor is for 20 minutes in the worst case, you just worked with it, next time you get to it you wont remember it and the time will be doubled...

**Comment by mcada** [comment]
@mastepan please fix the algorithm so it is stable or close the PR and create another one with fix for this scenario

**Pull request closed without merging**
