### PR TITLE
Fixes after DataMapper update

### PR DESCRIPTION
**Pull request by mkralik3**
* Remove reproducers for won't fix issue
* Fix DataMapper property
* Change DataMapper property to DataMapper constant since properties work differently now
* Fix incorrect parallelization for servicenow in maxIntegratiosn test
* Fix for external jaeger

//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by mmuzikar — APPROVED** [review]

**Pull request merged**
