### PR TITLE
[Box] Fix s3-box scenario

### PR DESCRIPTION
**Pull request by avano**
//test: `@s3 or @ENTESB-12553`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
