### PR TITLE
[ui] fixed oauth tests

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@oauth`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@mmuzikar my bad, I broke the parsing of the comment, in the meantime I edited the description :grin:

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connections - OAuth | Testing Twitter OAuth connector 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
Twitter connection fails from time to time, you can take a look at the logs the integration ran and just didn't react to any mentions.

**Pull request merged**
