### PR TITLE
[ui] api-provider modification still had some integrations running

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@api-provider`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | API Provider DELETE  - known issue
API Provider Integration | API Provider Edit OpenAPI - add operation 
API Provider Integration | Publishing an integration with all operations deleted should not be possible 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
retest this please

**Comment by mmuzikar** [comment]
@mkralik3 this will also help stabilize a test that failed from time to time

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | API Provider DELETE  - known issue
API Provider Integration | API Provider export roundtrip 
API Provider Integration | API Provider Edit OpenAPI - add operation 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
