### PR TITLE
[AWS-DDB] Fix failing aws-ddb tests

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@dynamodb`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Dynamodb connector | Webhook to dynamoDb - create item 
Dynamodb connector | Webhook to dynamoDb - query item 
Dynamodb connector | Webhook to dynamoDb - delete item 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Dynamodb connector | Webhook to dynamoDb - create item 
Dynamodb connector | Webhook to dynamoDb - query item 
Dynamodb connector | Webhook to dynamoDb - delete item 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Dynamodb connector | Webhook to dynamoDb - create item 
Dynamodb connector | Webhook to dynamoDb - query item 
Dynamodb connector | Webhook to dynamoDb - delete item 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Dynamodb connector | Webhook to dynamoDb - create item 
Dynamodb connector | Webhook to dynamoDb - query item 
Dynamodb connector | Webhook to dynamoDb - delete item 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@mkralik3 the test failures are caused due to the execution of PR tests against older syndesis version. The ER1 does contain the AWS-ddb name update.

**Pull request merged**
