### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Can one of the admins verify this patch?

**Comment by jstastny-cz** [comment]
@mkralik3 could you please also add note near 'cd syndesis-extensions' that the dir actually sits in syndesis-qe repo. It's not mentioned anywhere

**Comment by mkralik3** [comment]
The mention about submodule and plugins were added to the Prerequisites. Also, the note about submodule was added to the paragraph Before execution.

**Comment by mkralik3** [comment]
Rebased with the master, (added info about SAR NAMESPACE to the remote section)

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
