### PR TITLE
[ui][new] OAuth flow test

### PR DESCRIPTION
**Pull request by mcada**

### CODE REVIEW

**Comment by mcada** [comment]
Test requires some new credentials, marked with  *     :

```
"Twitter Listener": {
    "service": "twitter",
    "properties": {
*      "screenName": "syndesis_listen",
      "consumerKey": "***",
      "consumerSecret": "***",
      "accessToken": "***",
      "accessTokenSecret": "***",
*      "login":"syndesis.bot+listen***",
*      "password":"***"

    }
  },
  "twitter_talky": {
    "service": "twitter",
    "properties": {
*    "screenName": "syndesis_talky",
      "consumerKey": "***",
      "consumerSecret": "***",
      "accessToken": "***",
      "accessTokenSecret": "***",
*      "login":"syndesis.bot+talky***",
*      "password":"***"

    }
  },
  "QE Salesforce": {
    "service": "salesforce",
    "properties": {
      "instanceUrl": "https://developer.salesforce.com",
      "loginUrl": "https://login.salesforce.com",
      "clientId": "***",
      "clientSecret": "***",
*      "userName": "***",
*      "password": "***"**
    }
  },


```

**Comment by mcada** [comment]
no more WIP

**Comment by mcada** [comment]
No more WIP as the test is done but we have to wait with merge for automation migration.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
