### PR TITLE
test checkstyle fail

### PR DESCRIPTION
**Pull request by avano**

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
Starting audit...
[ERROR] /mnt/hudson_workspace/workspace/syndesis-tests-runner/syndesis-qe/rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java:83:23: '!=' is not followed by whitespace. [WhitespaceAround]
[ERROR] /mnt/hudson_workspace/workspace/syndesis-tests-runner/syndesis-qe/rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java:83:23: '!=' is not preceded with whitespace. [WhitespaceAround]
[ERROR] /mnt/hudson_workspace/workspace/syndesis-tests-runner/syndesis-qe/rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java:135:67: 'properties' hides a field. [HiddenField]
Audit done.
Checkstyle ends with 3 errors.
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
Starting audit...
[ERROR] /mnt/hudson_workspace/workspace/syndesis-tests-runner/syndesis-qe/rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java:83:23: '!=' is not followed by whitespace. [WhitespaceAround]
[ERROR] /mnt/hudson_workspace/workspace/syndesis-tests-runner/syndesis-qe/rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java:83:23: '!=' is not preceded with whitespace. [WhitespaceAround]
[ERROR] /mnt/hudson_workspace/workspace/syndesis-tests-runner/syndesis-qe/rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java:135:67: 'properties' hides a field. [HiddenField]
Audit done.
Checkstyle ends with 3 errors.
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/
  AbstractStep.java:83:23: '!=' is not followed by whitespace. [WhitespaceAround]
rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/
  AbstractStep.java:83:23: '!=' is not preceded with whitespace. [WhitespaceAround]
rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/
  AbstractStep.java:135:67: 'properties' hides a field. [HiddenField]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request closed without merging**
