### PR TITLE
[install] increase timeout when cleaning syndesis namespace

### PR DESCRIPTION
**Pull request by mcada**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
why?

**Comment by mcada** [comment]
Because it kept shutting down my syndesis local installation. There is hardcoded 20s timeout in used library and if all resources are not gone, it will stop the whole testsuite with one single fail.

**Comment by mcada** [comment]
The same happened to @asmigala today more than once so we decided it needs to be fixed...

**Comment by avano** [comment]
and isn't it because of the problems with the operator today?

**Comment by mcada** [comment]
No, I encountered the issue before but couldn't reproduce it. Today it happened even with older syndesis tag.

**Comment by avano** [comment]
@asmigala I'm just curious as I didn't encounter it yet :grin:

**Pull request merged**
