### PR TITLE
[FUSEQE-8537] Bump amq-streams to 1.4

### PR DESCRIPTION
**Pull request by avano**
//test: `@kafka`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
