### PR TITLE
[webhook] Fix the webhook regex, to conform to the OCP 4.1. URL format

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@webhook-ui-url`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
