### PR TITLE
[refactor] refactor salesforce validation steps

### PR DESCRIPTION
**Pull request by mcada**
//test: `@salesforce`

### CODE REVIEW

**Comment by mcada** [comment]
fixed

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
