### PR TITLE
Rest tests update

### PR DESCRIPTION
**Pull request by avano**
//test: `@integration-http-sql-split`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert | <font color="red"><b>FAILED</b></font> | tplevko@redhat.com
Integration - HTTP | HTTP to SQL with split
Connection - CRUD | Credentials | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Create and delete | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu edit and view
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert | <font color="red"><b>FAILED</b></font> | tplevko@redhat.com
Integration - HTTP | HTTP to SQL with split
Connection - CRUD | Credentials | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Create and delete | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu edit and view
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Credentials | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Create and delete | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu edit and view
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
