### PR TITLE
[FUSEQE-2893] Fix UI tests after UI changes

### PR DESCRIPTION
**Pull request by avano**
//test: ` @integrations-log,@integrations-db-to-db,@integrations-db-to-db-mysql,@oauth-create-integration,@webhook-get,@amqp-connection-publish-subscribe-request,@concur,@db-connection-crud-2-read-create-oracle12,@tech-extension-create-integration-with-new-tech-extension,@mqtt-connection-publish-subscribe-request,@support-page`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@tplevko merge please, test failures are not related to this PR

**Comment by tplevko** [comment]
:+1:

**Pull request merged**
