### PR TITLE
Import/Export test for integrations using customizations

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@customizations-export-import`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/
  TechExtensionsListComponent.java:5: Extra separation in import group before 'com.codeborne.selenide.Condition.enabled' [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/
  ExtensionSteps.java:5: Extra separation in import group before 'com.codeborne.selenide.Condition.visible' [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@mmuzikar whats the status?

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/
  TechExtensionsListComponent.java:5: Extra separation in import group before 'com.codeborne.selenide.Condition.enabled' [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/
  ExtensionSteps.java:5: Extra separation in import group before 'com.codeborne.selenide.Condition.visible' [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
Sorry, I accidentally ran all PRs on duplicated pipeline and aborted them, that's why it send message `Build finished. Tests FAILED`. You can ignore this last `syndesisqe` comment.

**Pull request closed without merging**
