### PR TITLE
Fixed Conditional flow selectors

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@conditional-flow or @oauth`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Validate all credentials 
Connections - OAuth | Testing Twitter OAuth connector 
Connections - OAuth | Testing Google calendar OAuth connector 
Connections - OAuth | Testing Salesforce OAuth connector 
Concur Connector | Check message of concur get list action 
Concur Connector | Check message of concur get listitems action 
Concur Connector | Check if create and delete listitems actions work together 
Conditional flows - content base routing | Conditional flows icon test - move up 
Conditional flows - content base routing | Conditional flows icon test - delete 
Conditional flows - content base routing | Conditional flows icon test multiple moves 
Conditional flows - content base routing | Conditional flows - edit and update step 
Google Calendar Connector | Test Copy Event 
Google Calendar Connector | Test Get a specific Event 
Google Calendar Connector | Test Update event coming in 
Google Calendar Connector | Test get events action - poll_all on past events 
Google Calendar Connector | Test get events action - poll_updated on past events 
Google Calendar Connector | Test get events action - poll_all on future events 
Google Calendar Connector | Test get events action - poll_updated on future events 
Google Calendar Connector | Test get events action - poll_upcoming on future events 
Google Calendar Connector | Test get events action - poll_all on all events 
Google Calendar Connector | Test get events action - poll_updated on all events 
Google Calendar Connector | Test get events action - poll_upcoming on all events 
Google Calendar Connector | Test get events action - poll_query on all events 
Google Calendar Connector | Test get events action - poll events updated during runtime 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
Integration - Salesforce to DB | Create 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.tpl 
Integration - Twitter Direct Messages | Send direct message on twitter 
Integration - Twitter to Salesforce | Create 
Support page | Export diagnostic of single integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
Moving conditional flows doesn't work on latest
Google sheets issues are also reported 
Salesforce issues as well
Google calendar too

**Comment by asmigala** [comment]
> Moving conditional flows doesn't work on latest

Is that reported?

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connections - OAuth | Testing Google calendar OAuth connector 
Connections - OAuth | Testing Salesforce OAuth connector 
Concur Connector | Check message of concur get list action 
Concur Connector | Check message of concur get listitems action 
Concur Connector | Check if create and delete listitems actions work together 
Conditional flows - content base routing | Conditional flows icon test - move up 
Conditional flows - content base routing | Conditional flows icon test - delete 
Conditional flows - content base routing | Conditional flows icon test multiple moves 
Conditional flows - content base routing | Conditional flows - multiple flows 
Conditional flows - content base routing | Conditional flows - dropdown test 
Integration - Databucket | Error mark indicator 
Integration - Databucket | Create 
Integration - Databucket | Create extended 
Integration - data shapes propagation | Data shapes propagation 
Integration - data shapes propagation | Data shapes propagation into conditional flow 
Google mail Connector | Send an e-mail 
Google mail Connector | Receive an e-mail 
Google Calendar Connector | Test Copy Event 
Google Calendar Connector | Test Get a specific Event 
Google Calendar Connector | Test Update event coming in 
Google Calendar Connector | Test get events action - poll_all on past events 
Google Calendar Connector | Test get events action - poll_updated on past events 
Google Calendar Connector | Test get events action - poll_upcoming on past events 
Google Calendar Connector | Test get events action - poll_all on future events 
Google Calendar Connector | Test get events action - poll_updated on future events 
Google Calendar Connector | Test get events action - poll_upcoming on future events 
Google Calendar Connector | Test get events action - poll_all on all events 
Google Calendar Connector | Test get events action - poll_updated on all events 
Google Calendar Connector | Test get events action - poll_upcoming on all events 
Google Calendar Connector | Test get events action - poll_query on all events 
Google Calendar Connector | Test get events action - poll events updated during runtime 
Google Sheets Connector | create spreadsheet 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
Integration - Salesforce to DB | Create 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.tpl 
Integration - Twitter Direct Messages | Receive direct message on twitter 
Integration - Twitter Direct Messages | Send direct message on twitter 
Integration - Twitter to Database | Create integration from twitter to database 
Integration - Twitter to Salesforce | Create 
Settings OAuth | Fill OAuth settings and check immediately 
Settings OAuth | Fill OAuth settings and check after changing page 
Settings OAuth | Fill OAuth settings, remove and check immediately 
Settings OAuth | Fill OAuth settings, remove and check after changing page 
Settings OAuth | Fill Gmail OAuth settings, create connection and validate 
Settings OAuth | Fill Google Calendar OAuth settings, create connection and validate 
Settings OAuth | Fill Twitter OAuth settings, create connection and validate 
Support page | Export diagnostic of single integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connections - OAuth | Testing Google calendar OAuth connector 
Connections - OAuth | Testing Salesforce OAuth connector 
Concur Connector | Check message of concur get list action 
Concur Connector | Check message of concur get listitems action 
Concur Connector | Check if create and delete listitems actions work together 
Conditional flows - content base routing | Conditional flows icon test - move up 
Conditional flows - content base routing | Conditional flows icon test - delete 
Conditional flows - content base routing | Conditional flows icon test multiple moves 
Integration - Databucket | Create extended 
Integration - data shapes propagation | Data shapes propagation 
Integration - data shapes propagation | Data shapes propagation into conditional flow 
Google mail Connector | Send an e-mail 
Google mail Connector | Receive an e-mail 
Google Calendar Connector | Test Copy Event 
Google Calendar Connector | Test Get a specific Event 
Google Calendar Connector | Test Update event coming in 
Google Calendar Connector | Test get events action - poll_all on past events 
Google Calendar Connector | Test get events action - poll_updated on past events 
Google Calendar Connector | Test get events action - poll_upcoming on past events 
Google Calendar Connector | Test get events action - poll_all on future events 
Google Calendar Connector | Test get events action - poll_updated on future events 
Google Calendar Connector | Test get events action - poll_upcoming on future events 
Google Calendar Connector | Test get events action - poll_all on all events 
Google Calendar Connector | Test get events action - poll_updated on all events 
Google Calendar Connector | Test get events action - poll_upcoming on all events 
Google Calendar Connector | Test get events action - poll_query on all events 
Google Calendar Connector | Test get events action - poll events updated during runtime 
Google Sheets Connector | create spreadsheet 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
Integration - Salesforce to DB | Create 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.tpl 
Integration - Twitter Direct Messages | Receive direct message on twitter 
Integration - Twitter Direct Messages | Send direct message on twitter 
Integration - Twitter to Database | Create integration from twitter to database 
Integration - Twitter to Salesforce | Create 
Settings OAuth | Fill OAuth settings and check immediately 
Settings OAuth | Fill OAuth settings and check after changing page 
Settings OAuth | Fill OAuth settings, remove and check immediately 
Settings OAuth | Fill OAuth settings, remove and check after changing page 
Settings OAuth | Fill Gmail OAuth settings, create connection and validate 
Settings OAuth | Fill Google Calendar OAuth settings, create connection and validate 
Settings OAuth | Fill Twitter OAuth settings, create connection and validate 
Support page | Export diagnostic of single integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connections - OAuth | Testing Google calendar OAuth connector 
Connections - OAuth | Testing Salesforce OAuth connector 
Concur Connector | Check message of concur get list action 
Concur Connector | Check message of concur get listitems action 
Concur Connector | Check if create and delete listitems actions work together 
Conditional flows - content base routing | Conditional flows icon test - move up 
Conditional flows - content base routing | Conditional flows icon test - delete 
Conditional flows - content base routing | Conditional flows icon test multiple moves 
Google mail Connector | Receive an e-mail 
Google Calendar Connector | Test Copy Event 
Google Calendar Connector | Test Get a specific Event 
Google Calendar Connector | Test Update event coming in 
Google Calendar Connector | Test get events action - poll_all on past events 
Google Calendar Connector | Test get events action - poll_updated on past events 
Google Calendar Connector | Test get events action - poll_upcoming on past events 
Google Calendar Connector | Test get events action - poll_all on future events 
Google Calendar Connector | Test get events action - poll_updated on future events 
Google Calendar Connector | Test get events action - poll_upcoming on future events 
Google Calendar Connector | Test get events action - poll_all on all events 
Google Calendar Connector | Test get events action - poll_updated on all events 
Google Calendar Connector | Test get events action - poll_upcoming on all events 
Google Calendar Connector | Test get events action - poll_query on all events 
Google Calendar Connector | Test get events action - poll events updated during runtime 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
Integration - Salesforce to DB | Create 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.tpl 
Integration - Twitter Direct Messages | Receive direct message on twitter 
Integration - Twitter Direct Messages | Send direct message on twitter 
Integration - Twitter to Database | Create integration from twitter to database 
Integration - Twitter to Salesforce | Create 
Settings OAuth | Fill OAuth settings and check immediately 
Settings OAuth | Fill OAuth settings and check after changing page 
Settings OAuth | Fill OAuth settings, remove and check immediately 
Settings OAuth | Fill OAuth settings, remove and check after changing page 
Settings OAuth | Fill Gmail OAuth settings, create connection and validate 
Settings OAuth | Fill Google Calendar OAuth settings, create connection and validate 
Settings OAuth | Fill Twitter OAuth settings, create connection and validate 
Support page | Export diagnostic of single integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
@asmigala yes it is and there should also be a fix for that already.

**Comment by asmigala** [comment]
Lgtm then

**Pull request merged**
