### PR TITLE
[FUSEQE-8366] - Add clean up after Camel-k test

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@camel-k or @activity-test`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Camel-k Runtime | Extensions shouldn't be visible 
Activity | Check activity 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Camel-k Runtime | Extensions shouldn't be visible 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
Duplicate https://github.com/syndesisio/syndesis-qe/pull/1369

**Pull request closed without merging**
