### PR TITLE
[FUSEQE-8681] pf4 migration - activity, metrics, public api, connecti…

### PR DESCRIPTION
**Pull request by mkralik3**
…ons, oauth

* Migration of the activity, metrics, publicApi, connections and settings-oauth tests to pf4
* OAuth settings page was refactored

Without changes in `dataTestId`.  `dataTestId` will be added for activity, metrics, public api in the next PR (when I will successfully manage to set up environment  :D )

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by Stefan365** [comment]
as far as it works, it looks good to me.

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
