### PR TITLE
Workaround for generating reports

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@ui`
DO NOT MERGE.
@Stefan365 you can find the resulting report in <link to job>/artifact/results/results-pr/syndesis-qe/results/ui/testid_rewrite.html

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - API key 
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - OAuth 2  - known issue
Integration - AMQ to REST | Publish subscribe on topic 
API Provider Integration | API Provider DELETE  - known issue
API Provider Integration | Publishing an integration without any operation should not be possible 
Concur Connector | Check message of concur get list action 
Concur Connector | Check message of concur get listitems action 
Concur Connector | Check if create and delete listitems actions work together 
Integration - Databucket | Create 
Integration - Databucket | Create extended 
Integration - DB to DB mysql | Read and create operations 
Dynamodb connector | Webhook to dynamoDb - query item  - known issue
Integration - Import Export | Import and export drag and drop 
Integration - Import Export | Import from different syndesis instance 
Integration - Status | Check starting integration status on detail page 
Integration - Status | Check starting integration status on integration list 
Integration - Status | Check starting integration status on home page 
Jira Connector | Comment on a Jira issue 
Jira Connector | Add a new jira issue 
Jira Connector | Comment on a Jira issue 
Jira Connector | Retreive new comments from a Jira issue 
Jira Connector | Retrieve New Issues 
Kudu connector | Insert data into kudu table 
Kudu connector | Scan kudu table 
Kudu connector | Kudu integration with mqtt 
Log Connector | Check log message with body: true and context: true 
Log Connector | Check log message with body: true and context: false 
Log Connector | Check log message with body: false and context: true 
Log Connector | Check log message with body: false and context: false 
Log Connector | Check log without message 
Integration - MQTT to MQTT | Publish subscribe on topic 
OData Connector | Read entity collection from OData service tests 
OData Connector | Read single entity from OData service tests 
OData Connector | Read property of entity from OData service tests 
OData Connector | Read with $expand query from OData service tests 
OData Connector | Create entity in OData service 
OData Connector | Delete entity in OData service 
OData Connector | Read wrong_datashape from OData service tests 
OData Connector | Read NPE from OData service tests 
OData Connector | Read string predicate without quotes from OData service tests 
OData Connector | Read enum mapping from OData service tests 
OData Connector | OData connector needs server certificate 
Integration - Openwire to Openwire | Publish subscribe on queue 
Integration - Salesforce to DB | Create 
Integration - ServiceNow-amq/log | Get incident from service now 
Integration - ServiceNow-amq/log | Create incident from syndesis integration 
Slack Connector | Check that slack received a message from an integration 
Slack Connector | Check that slack message is saved into DB 
Slack Connector | Check Maximum Messages to Retrieve and Delay function in SLACK consumer 
Integration - DB to DB with split/aggregate | Split and aggregate integration flow 
SQL Connector | Check SQL pulls all rows 
SQL Connector | Check SQL connector with predicate id < :#id 
SQL Connector | Check SQL connector with predicate id > :#id 
SQL Connector | Check SQL connector with predicate id <= :#id 
SQL Connector | Check SQL connector with predicate id >= :#id 
SQL Connector | Check SQL connector with predicate id != :#id 
SQL Connector | Check SQL connector with predicate id <= :#id AND id > 1 
SQL Connector | Check SQL connector with predicate id BETWEEN :#id AND 4 
SQL Connector | Check SQL connector with predicate id <= :#id OR id = 5 
SQL Connector | Check SQL connector with predicate :#id > id  - known issue
SQL Connector | Check SQL connector with predicate (id+1) < :#id  - known issue
SQL Connector | Check SQL connector with predicate id in (1, :#id)  - known issue
SQL Connector | Check SQL connector with predicate id = floor(:#id)  - known issue
SQL Connector | Return generated keys for INSERT statement 
SQL Connector | Return generated keys for INSERT statement from start step 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt 
Templates | Verify that the code editor for templates is working correctly  - known issue
Integration - Twitter Direct Messages | Receive direct message on twitter 
Integration - Twitter Direct Messages | Send direct message on twitter 
Integration - Twitter to Database | Create integration from twitter to database 
Integration - Twitter to Salesforce | Create 
Integration - Webhook to API connector | Webhook to Custom API connector 
Integration - Webhook to API connector | Test to reproduce #3727 
Integration - Webhook to DB | Webhook to db with middle db step 
Integration - Webhook to DB | Webhook to db with batch insert 
3scale integration | 3scale discovery annotations 
Activity | Check activity 
Activity | Check error 
Activity | Check whether shows error when data mapper is before 
Metrics | Check metrics 
Metrics | Check error 
Login logout | Log out 
Login logout | Log out and log in 
Test tagging integration in CI CD dialog | Test creating new tag 
Test tagging integration in CI CD dialog | Test updating tag in CI CD dialog 
Test tagging integration in CI CD dialog | Test checking tag in CI CD dialog 
Test tagging integration in CI CD dialog | Test unchecking tag in CI CD dialog and whether it is still exist when no integration uses it 
Test tagging integration in CI CD dialog | Test deleting tag in CI CD dialog 
Test tagging integration in CI CD dialog | Test check and delete multiple tag across integrations 
Test tagging integration in CI CD dialog | Test check number of tag 
Import and export integration test | Test export the integrations according to tag and import it again 
Import and export integration test | Test export the all integrations and import it again 
Settings OAuth | Fill OAuth settings and check immediately 
Settings OAuth | Fill OAuth settings and check after changing page 
Settings OAuth | Fill OAuth settings, remove and check immediately 
Settings OAuth | Fill OAuth settings, remove and check after changing page 
Settings OAuth | Fill Gmail OAuth settings, create connection and validate 
Settings OAuth | Fill Google Calendar OAuth settings, create connection and validate 
Settings OAuth | Fill Twitter OAuth settings, create connection and validate 
Support page | Version 
Support page | Export diagnostic of all 
Support page | Export diagnostic of single integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - OAuth 2  - known issue
Integration - AMQ to REST | Publish subscribe on topic 
API Provider Integration | API Provider DELETE  - known issue
Concur Connector | Check message of concur get list action 
Concur Connector | Check message of concur get listitems action 
Concur Connector | Check if create and delete listitems actions work together 
Integration - Databucket | Create extended 
Integration - DB to DB mysql | Read and create operations 
Dynamodb connector | Webhook to dynamoDb - query item  - known issue
Google Calendar Connector | Test Copy Event 
Google Calendar Connector | Test Get a specific Event 
Google Calendar Connector | Test get events action - poll_updated on all events 
Integration - Import Export | Import and export drag and drop 
Integration - Import Export | Import from different syndesis instance 
Jira Connector | Comment on a Jira issue 
Jira Connector | Add a new jira issue 
Jira Connector | Comment on a Jira issue 
Jira Connector | Retreive new comments from a Jira issue 
Jira Connector | Retrieve New Issues 
Log Connector | Check log message with body: false and context: false 
OData Connector | Read property of entity from OData service tests 
SQL Connector | Check SQL connector with predicate id > :#id 
SQL Connector | Check SQL connector with predicate id <= :#id 
SQL Connector | Check SQL connector with predicate id >= :#id 
SQL Connector | Check SQL connector with predicate id != :#id 
SQL Connector | Check SQL connector with predicate id <= :#id OR id = 5 
SQL Connector | Check SQL connector with predicate :#id > id  - known issue
SQL Connector | Check SQL connector with predicate (id+1) < :#id  - known issue
SQL Connector | Check SQL connector with predicate id in (1, :#id)  - known issue
SQL Connector | Check SQL connector with predicate id = floor(:#id)  - known issue
Templates | Verify that the code editor for templates is working correctly  - known issue
Metrics | Check error 
Test tagging integration in CI CD dialog | Test updating tag in CI CD dialog 
Test tagging integration in CI CD dialog | Test checking tag in CI CD dialog 
Test tagging integration in CI CD dialog | Test unchecking tag in CI CD dialog and whether it is still exist when no integration uses it 
Test tagging integration in CI CD dialog | Test deleting tag in CI CD dialog 
Test tagging integration in CI CD dialog | Test check and delete multiple tag across integrations 
Test tagging integration in CI CD dialog | Test check number of tag 
Import and export integration test | Test export the integrations according to tag and import it again 
Import and export integration test | Test export the all integrations and import it again 
Support page | Version 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
This is obsolete, there's an option for that in Jenkins

**Pull request closed without merging**
