### PR TITLE
[ui][camelk] Added CamelK smoke test

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@camel-k-smoke`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Disconnected install | Camel-K 
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Camel-k Runtime | Extensions shouldn't be visible 
Camel-k Runtime | CamelK smoke test 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Camel-k Runtime | CamelK smoke test 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Camel-k Runtime | CamelK smoke test 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Camel-k Runtime | CamelK smoke test 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Camel-k Runtime | CamelK smoke test 
```

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/
  WizardSteps.java:28: @And should not be used. [RegexpSingleline]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/
  WizardSteps.java:37: @And should not be used. [RegexpSingleline]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/
  WizardSteps.java:46: @And should not be used. [RegexpSingleline]
```

**Pull request merged**
