### PR TITLE
[ui]add new integration test AMQ-REST API (todo app)

### PR DESCRIPTION
**Pull request by mkralik3**
tutorial integration AMQ to REST API (todo app)
contains extension and custom API (todo app) via URL

//test: @integrations-amq-to-rest

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@mkralik3 there was an issue with chrome-driver, which is merged into master already, please rebase your commit to master

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
