### PR TITLE
[REST]Fix namespace in deleting cluster role bindings method

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@publicapi and @rest`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
@mkralik3 please rebase to latest master.. there were changes to binary client due to the switch from `xtf.utils` to `xtf.core`

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - connections point | Change connection properties 
Public API - environments point | Get all tags from Syndesis 
Public API - environments point | Get all tags with the number of usages 
Public API - environments point | Get all tags from Syndesis without duplicates 
Public API - environments point | Add new tag to the Syndesis 
Public API - environments point | Update tag in all integration 
Public API - environments point | Delete tag from all integrations 
Public API - integrations point | Add and get tags in integration 
Public API - integrations point | Update tags on integration without remove previous 
Public API - integrations point | Update tags on integration uncheck previous 
Public API - integrations point | Delete tag from integration 
Public API - integrations point | Stop integration 
Public API - integrations point | Deploy and redeploy integration 
Public API - integrations point | Export and import integrations according to tag 
Public API - integrations point | Export and import all integrations from Syndesis according to tag 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - connections point | Change connection properties 
Public API - environments point | Get all tags from Syndesis 
Public API - environments point | Get all tags with the number of usages 
Public API - environments point | Get all tags from Syndesis without duplicates 
Public API - environments point | Add new tag to the Syndesis 
Public API - environments point | Update tag in all integration 
Public API - environments point | Delete tag from all integrations 
Public API - integrations point | Add and get tags in integration 
Public API - integrations point | Update tags on integration without remove previous 
Public API - integrations point | Update tags on integration uncheck previous 
Public API - integrations point | Delete tag from integration 
Public API - integrations point | Stop integration 
Public API - integrations point | Deploy and redeploy integration 
Public API - integrations point | Export and import integrations according to tag 
Public API - integrations point | Export and import all integrations from Syndesis according to tag 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
After rebase, the endpoint for deleting tag returns 302, I have to investigate why

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - environments point | Update tag in all integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
