### PR TITLE
[FUSEQE-8363] SFTP test stabilization

### PR DESCRIPTION
**Pull request by Stefan365**
//test: `@integrations-sftp-to-sftp`

explanation: I cannot reproduce this sftp connection instability problem on local -> OCP, so I need to utilize jenkins. 
Since it's random problem, I'll retest this several times.

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by Stefan365** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by Stefan365** [comment]
retest this please

**Comment by Stefan365** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by Stefan365** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by Stefan365** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
Integration - SFTP to SFTP | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by Stefan365** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by Stefan365** [comment]
test seems to be stabilized (FAILED^^ due to other reason)

**Pull request merged**
