### PR TITLE
Added tags for compontents to UI tests

### PR DESCRIPTION
**Pull request by mkralik3**
* Tags was added to the UI tests
  * All tests in the integration folder starts with integrations-
  * Fix regex for activity test

//test: `@integrations-slack,@activity`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@mkralik3 I edited your comment from:

`//test: @blabla`

to the correct syntax

//test: `@blabla`

**Comment by avano** [comment]
retest this please

**Comment by mkralik3** [comment]
:( my bad, upravil som znova readme

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
