### PR TITLE
[Fixes] Fix editing DC and polling SQS

### PR DESCRIPTION
**Pull request by avano**
//test: `@integration-sqs-sqs-max-objects or @integration-http-consumer-delete`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
validation/src/main/java/io/syndesis/qe/validation/
  SQSValidationSteps.java:92:9: 'for' is not followed by whitespace. [WhitespaceAround]
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - SQS | SQS to SQS Max objects to poll 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by mkralik3 — APPROVED** [review]

**Pull request merged**
