### PR TITLE
[FUSEQE-8537] Bump amq-streams to 1.4

### PR DESCRIPTION
**Pull request by avano**
//test: `@kafka`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by mkralik3** [comment]
@avano Can you please backport the `transportProtocol` change also to the 1.9.x and 1.10.x branches where the origin commit was already merged ?

**Comment by avano** [comment]
@mkralik3 that option is only in master

**Pull request merged**
