### PR TITLE
[Monitoring] Edit test to work with Jaeger

### PR DESCRIPTION
**Pull request by avano**
//test: `@integration-db-to-db-monitoring`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@avano Since the Jaeger is enabled by default, the test will be skipped every time.  Can we, instead of skipping the test, add log step into the integration and little update `validate that log of integration "([^"]*)" has been created, period in ms:` step?

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
