### PR TITLE
[FUSEQE-5666] Add test for box download datamapper

### PR DESCRIPTION
**Pull request by avano**
//test: `@box`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - File transfer | SQL to Box download to AMQ 
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
