### PR TITLE
[FUSEQE-6941] - reproducers for ENTESB-11415, ENTESB-11447, ENTESB-11…

### PR DESCRIPTION
**Pull request by mkralik3**
…253, ENTESB-12005

//test: `@ENTESB-11415 or @ENTESB-11447 or @ENTESB-11253 or @ENTESB-12005`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
