### PR TITLE
ui: added tests for OAuth Settings

### PR DESCRIPTION
**Pull request by jstastny-cz**
//test: @oauth,@settings-oauth

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jstastny-cz** [comment]
3 tests failing due to https://github.com/syndesisio/syndesis/issues/4021.

**Comment by jstastny-cz** [comment]
Don't merge, need to run also @oauth as part of verification. Another commit coming.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jstastny-cz** [comment]
The three failures are due to https://github.com/syndesisio/syndesis/issues/4021

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@jstastny-cz can you rebase & fix conflicts please?

**Comment by jstastny-cz** [comment]
@avano I will add also tags for the failing tests, wait, please :-D

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jstastny-cz** [comment]
@avano yep, poor rebase skills :-(

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
