### PR TITLE
[fix] - fixed creation of a zip file

### PR DESCRIPTION
**Pull request by mkralik3**
* added check whether the zip file was created successfully

//test: `@publicapi`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert
Connection - CRUD | Credentials | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
Will be as part of Public API UI test migration from 1.6.x to the master

**Pull request closed without merging**
