### PR TITLE
[SQS] Increase timeouts for sqs tests

### PR DESCRIPTION
**Pull request by avano**
//test: `@integration-amq-sqs-send-delay or @integration-sqs-sqs-delete-after-read`

### CODE REVIEW

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by mkralik3 — APPROVED** [review]

**Pull request merged**
