### PR TITLE
Fix @integration-check-starting-status

### PR DESCRIPTION
**Pull request by mastepan**
//test: `@integration-check-starting-status`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Check starting integration status on integration list 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mastepan** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by asmigala** [comment]
already fixed in #1003, closing

**Pull request closed without merging**
