### PR TITLE
Remove gh-6141 workaround

### PR DESCRIPTION
**Pull request by asmigala**
//test: `@integrations-ftp-to-ftp`

Can only be tested once our test suite works with 1.8, as the issue is not fixed in 1.7

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - FTP to FTP | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - FTP to FTP | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - FTP to FTP | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
Sorry, I accidentally ran all PRs on duplicated pipeline and aborted them, that's why it send message `Build finished. Tests FAILED`. You can ignore this last `syndesisqe` comment.

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - FTP to FTP | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
