### PR TITLE
[FUSEQE-7152] API client authentication - basic password

### PR DESCRIPTION
**Pull request by AnetaCadova**
//test: `@api-client-auth-basic-password`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by AnetaCadova** [comment]
This test will fail until the PR https://github.com/syndesisio/syndesis-qe-HTTPEndpoints/pull/2 is merged.

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | Basic password used in API client 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | Basic password used in API client 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | Basic password used in API client 
```

**Comment by mkralik3** [comment]
@AnetaCadova  please rebase this with the latest 1.12.x . It looks that the test is failing due to atlasmap changes.

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | Basic password used in API client 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | Basic password used in API client 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Kebab menu edit and view 
Testing authentication options of API client | Basic password used in API client 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | Basic password used in API client 
```

**Pull request merged**
