### PR TITLE
[FUSEQE-6350] - added delay to the CICD dialog page

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@cicddialog`

### CODE REVIEW

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
@tplevko it looks like a problem with one smoke test. The same test failed in another PR https://github.com/syndesisio/syndesis-qe/pull/1166 . However, the failed test is not related to this issue so can I close this one?

**Comment by mkralik3** [comment]
@tplevko I wanted to add a comment to the https://github.com/syndesisio/syndesis-qe/pull/1165 :D .. anyway. I will merge it too.

**Pull request merged**
