### PR TITLE
fix @create-delete-api-connector (wait for modalDialog to be closed) 1.6.x

### PR DESCRIPTION
**Pull request by mastepan**
//test: `@create-delete-api-connector`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mastepan** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mcada** [comment]
@mastepan what is the point of this fix? The test is passing already and your changes do exactly the same thing as the previous code but you try to wait until modal window is visible.

First of all it already works so I am closing the PR.
Second point - you can just use `OpenShiftWaitUtils.waitFor(() -> modalDialogPage.validate(), 15 * 1000L);` and fail the test if its not visible and get rid of the for cycle

**Pull request closed without merging**
