### PR TITLE
Fix waiting for server redeployment

### PR DESCRIPTION
**Pull request by jsafarik**
//test: `@3scale or @activity-test`

### CODE REVIEW

**Comment by mkralik3** [comment]
LGTM, @avano can you verify it too? just for sure.

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - DB to DB | Read and update operations 
Activity | Check activity 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
looks ok to me as well. should I merge?

**Comment by mkralik3** [comment]
@avano yes

**Pull request merged**
