### PR TITLE
Add test for ENTESB-14559

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@integration-labels`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/
  CreateIntegration.java:12:8: Unused import - com.codeborne.selenide.ElementsCollection. [UnusedImports]
ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/
  CreateIntegration.java:15:8: Unused import - java.util.ArrayList. [UnusedImports]
ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/
  CreateIntegration.java:67:39: '{' is not preceded with whitespace. [WhitespaceAround]
ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/
  CreateIntegration.java:74:42: '{' is not preceded with whitespace. [WhitespaceAround]
ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/
  CreateIntegration.java:80:39: '{' is not preceded with whitespace. [WhitespaceAround]
ui-common/src/main/java/io/syndesis/qe/steps/integrations/editor/
  CreateIntegrationSteps.java:9:8: Unused import - org.openqa.selenium.By. [UnusedImports]
ui-common/src/main/java/io/syndesis/qe/steps/integrations/editor/
  CreateIntegrationSteps.java:11:8: Unused import - com.codeborne.selenide.ElementsCollection. [UnusedImports]
ui-common/src/main/java/io/syndesis/qe/steps/integrations/editor/
  CreateIntegrationSteps.java:17: Wrong order for 'io.cucumber.datatable.DataTable' import. [ImportOrder]
validation/src/main/java/io/syndesis/qe/validation/
  OpenshiftValidationSteps.java:349:31: Unnecessary parentheses around lambda value. [UnnecessaryParentheses]
```

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
validation/src/main/java/io/syndesis/qe/validation/
  OpenshiftValidationSteps.java:351:31: Unnecessary parentheses around lambda value. [UnnecessaryParentheses]
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-common/src/main/java/io/syndesis/qe/steps/
  CommonSteps.java:1002:72: '{' is not preceded with whitespace. [WhitespaceAround]
```

**Pull request merged**
