### PR TITLE
FUSEQE-9312 Fix 10-integrations-complex test and replace odata with servicenow

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@mmuzikar  result for prod version is here: https://fuse-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fuse-7.7-syndesis-tests-firefox/436/

**Pull request merged**
