### PR TITLE
 Add databuckets in datamapper for API Import/Export test and fix Operator Metrics rest test

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@import-export-open-api`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration - Import Export | Create an integration with custom API connector and then export and import the integration 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration - Import Export | Create an integration with custom API connector and then export and import the integration 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration - Import Export | Create an integration with custom API connector and then export and import the integration 
```

**Comment by mkralik3** [comment]
Error: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend. 
:/

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
retest this please

**Pull request merged**
