### PR TITLE
[ui] Added regressions tests for several issues

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@api-provider-finish-replace or @data-mapper-reconfigure or @api-provider-post-existing`

### CODE REVIEW

**Comment by mmuzikar** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Data Mapper | Check reconfiguring datamapper doesn't delete the mappings 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Data Mapper | Check reconfiguring datamapper doesn't delete the mappings 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@mmuzikar Please, create also a backport for this PR.

**Pull request merged**
