### PR TITLE
Backport UI dockerfile for 1.11.x

### PR DESCRIPTION
**Pull request by mkralik3**
Backport for: https://github.com/syndesisio/syndesis-qe/pull/1564

//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@avano  I have removed the internal repo URL for now. Can you please merge this in case everything else is correct?

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by avano — APPROVED** [review]

**Pull request merged**
