### PR TITLE
fix @tech-extension-create-integration-with-new-tech-extension

### PR DESCRIPTION
**Pull request by mastepan**
//test: `@tech-extension-create-integration-with-new-tech-extension`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mastepan** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request closed without merging**
