### PR TITLE
[ui][react] Fix google calendar tests

### PR DESCRIPTION
**Pull request by asmigala**
//test: `@google-calendar`

Contains a workaround for oauth creation issues.

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
I left out the `Contains a workaround for oauth creation issues.` from the description and I'll fix the parsing later

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Calendar Connector | Test Get a specific Event 
Google Calendar Connector | Test Update event coming in 
Google Calendar Connector | Test get events action - poll_all on past events 
Google Calendar Connector | Test get events action - poll_updated on past events 
Google Calendar Connector | Test get events action - poll_upcoming on past events 
Google Calendar Connector | Test get events action - poll_all on future events 
Google Calendar Connector | Test get events action - poll_updated on future events 
Google Calendar Connector | Test get events action - poll_upcoming on future events 
Google Calendar Connector | Test get events action - poll_all on all events 
Google Calendar Connector | Test get events action - poll_updated on all events 
Google Calendar Connector | Test get events action - poll_upcoming on all events 
Google Calendar Connector | Test get events action - poll_query on all events 
Google Calendar Connector | Test get events action - poll events updated during runtime 
Settings OAuth | Fill OAuth settings, remove and check after changing page 
Settings OAuth | Fill Gmail OAuth settings, create connection and validate 
Settings OAuth | Fill Google Calendar OAuth settings, create connection and validate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Settings OAuth | Fill Gmail OAuth settings, create connection and validate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
Test failed due to known open issue

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Settings OAuth | Fill OAuth settings, remove and check immediately 
Settings OAuth | Fill Gmail OAuth settings, create connection and validate  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Settings OAuth | Fill Gmail OAuth settings, create connection and validate  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
