### PR TITLE
Added test for GH - #3786

### PR DESCRIPTION
**Pull request by mkralik3**
The test for https://github.com/syndesisio/syndesis/issues/3786 

//test: @log-connector-no-message

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
Only rest smoke test failed, it looks like not a problem with this PR.

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mcada** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
