### PR TITLE
[FIX] Fix Google Calendar tests

### PR DESCRIPTION
**Pull request by Stefan365**
//test: `@google-calendar-copy-event or @google-calendar-update-event-coming-in`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
@Stefan365 the tests failed due to a problem in the cucumber tag format, could you please edit the description and remove the parenthesis? Not sure that will help but it might

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Calendar Connector | Test Copy Event  - known issue
Google Calendar Connector | Test Update event coming in  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
