### PR TITLE
[FUSEQE-6286] Fix twitter direct message send

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@twitter-direct-messages-send`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
@tplevko are you sure it should be backported to 1.7.x?

**Comment by tplevko** [comment]
@avano I thought this was already a new branch for 7.5., now I realized the name would be 1.8.x. Seems like it's not really relevant for 1.7.x

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
