### PR TITLE
[FUSEQE-5979] Part 1, new ftp server

### PR DESCRIPTION
**Pull request by Stefan365**
Old ftp server was slow, so new one is to be deployed.

//test: `@ftp`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Can one of the admins verify this patch?

**Comment by avano** [comment]
ok to test

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - FTP to FTP | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
