### PR TITLE
reproducers for gh-5151 and gh-5067

### PR DESCRIPTION
**Pull request by jsafarik**
//test: `@gh-5151 or @gh-5067`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData Connector | Map complex properties 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData Connector | Map complex properties 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Validate all credentials 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
OData Connector | Map complex properties 
OData Connector | Read complex property 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request closed without merging**
