### PR TITLE
Fixed conditional flow steps

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@conditional-flow`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Conditional flows - content base routing | Conditional flows - functional test 
Conditional flows - content base routing | Conditional flows - delete step 
Conditional flows - content base routing | Conditional flows - edit and update step 
Conditional flows - content base routing | Conditional flows - output type 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Conditional flows - content base routing | Conditional flows - delete step 
Conditional flows - content base routing | Conditional flows - edit and update step 
Conditional flows - content base routing | Conditional flows - output type 
```

**Comment by mmuzikar** [comment]
`check that conditional flow step contains 3 flows` will be fixed when new image finishes builidng

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Conditional flows - content base routing | Conditional flows - delete step 
Conditional flows - content base routing | Conditional flows - edit and update step 
```

**Pull request merged**
