### PR TITLE
Fix @integrations-check-starting-status tests

### PR DESCRIPTION
**Pull request by mastepan**
//test: `@integrations-check-starting-status`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/
  CreateIntegrationSteps.java:5: Wrong order for 'io.syndesis.qe.fragments.common.form.Form' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/
  CreateIntegrationSteps.java:8: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mastepan** [comment]
retest this please

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/
  CreateIntegrationSteps.java:5: Extra separation in import group before 'io.cucumber.datatable.DataTable' [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/
  CreateIntegrationSteps.java:6: Wrong order for 'io.syndesis.qe.fragments.common.form.Form' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mastepan** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mastepan** [comment]
I've just rebased this branch to master after the last tests passed. Should be ok.

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Check starting integration status on detail page 
Integration - DB to DB | Check starting integration status on integration list 
Integration - DB to DB | Check starting integration status on home page 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
