### PR TITLE
[FUSEQE-6921] Add manual scenario for 3scale testing according to doc…

### PR DESCRIPTION
**Pull request by jsafarik**
…umentation

//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
Please, add here 
https://github.com/syndesisio/syndesis-qe/blob/master/ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java#L189
option for login in 3scale cluster in order to have `log into the Syndesis` step automatized

**Comment by jsafarik** [comment]
Fix with logging in added

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
