### PR TITLE
[UI-tests]Fix apicurio tests

### PR DESCRIPTION
**Pull request by mmajerni**
Signed-off-by: mmajerni <mmajerni@redhat.com>

//test: `@apicurio`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmajerni** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@mmajerni you were missing backticks in the //test directive:

was:

//test: @Apicurio

should be:

//test: `@Apicurio`

I edited your comment

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@mmajerni can you please have a look at the two last failing apicurio tests? Thanks!

**Comment by tplevko** [comment]
@mmajerni :1st_place_medal:

**Pull request merged**
