### PR TITLE
[ui][fix] fix import-export tests

### PR DESCRIPTION
**Pull request by mcada**
//test: `@integration-import-export`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Import Export | Import and export drag and drop 
Integration - Import Export | Import from different syndesis instance 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Import Export | Import and export drag and drop 
Integration - Import Export | Import from different syndesis instance 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
Merging anyway, drag and drop is broken and the other test passes on localhost. YOLO.

**Pull request merged**
