### PR TITLE
[fix] post existing - affected by ENTESB-11675, and added 2 waits

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@api-provider-get-collection or @sql-connector-predicates`

Just annotated one of the tests - it's affected by an yet unhandled error response from DB connector and added 2 waits - to solve issue in api-provider-get-collection and sql-connector-predicates.

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu edit and view 
API Provider Integration | API Provider GET collection 
Integration - DB to DB | Read and update operations 
SQL Connector | Check SQL connector with predicate id < :#id 
SQL Connector | Check SQL connector with predicate id > :#id 
SQL Connector | Check SQL connector with predicate id <= :#id 
SQL Connector | Check SQL connector with predicate id >= :#id 
SQL Connector | Check SQL connector with predicate id != :#id 
SQL Connector | Check SQL connector with predicate id <= :#id AND id > 1 
SQL Connector | Check SQL connector with predicate id BETWEEN :#id AND 4 
SQL Connector | Check SQL connector with predicate id <= :#id OR id = 5 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
