### PR TITLE
[WIP] [api-provider] Fix failing tests and introduce new ones

### PR DESCRIPTION
**Pull request by asmigala**
Depends on https://github.com/Apicurio/apicurio-qe/pull/5 and ci-ops-fuse MR #428

//test: `@api-provider`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by asmigala** [comment]
@tplevko no point retesting this one, I'm still trying to make the tests work on the 1.6.x branch and then will update this PR.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request closed without merging**
