### PR TITLE
[FUSEQE-7947] apicurito steps investigation

### PR DESCRIPTION
**Pull request by AnetaCadova**
These two removed steps were duplicate of the "change frame to " step. 
//test: `@apicurio`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
@AnetaCadova please rebase with 2.x

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | API key used in API client provided in query 
Testing authentication options of API client | API key used in API client provided in headers 
Customization - API Connector - ApicurIO GUI | Check if warnings change is propagated into connector review page from ApicurIO GUI 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by mkralik3 — APPROVED** [review]

**Pull request merged**
