### PR TITLE
[ui][fix] fix api client connectors crud feature

### PR DESCRIPTION
**Pull request by mcada**
//test: `@api-connector-crud`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/
  ApiSpecificationForm.java:5: Wrong order for 'org.openqa.selenium.By' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/
  ApiSpecificationForm.java:6: Wrong order for 'com.codeborne.selenide.Selenide.$' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/
  ApiClientConnectorDetail.java:12: Wrong order for 'io.syndesis.qe.pages.SyndesisPageObject' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/
  SpecifySecurity.java:81:25: Unnecessary parentheses around lambda value. [UnnecessaryParentheses]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:199:48: String literal expressions should be on the left side of an equalsIgnoreCase comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:200:48: String literal expressions should be on the left side of an equalsIgnoreCase comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:236:61: String literal expressions should be on the left side of an equalsIgnoreCase comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:237:55: String literal expressions should be on the left side of an equalsIgnoreCase comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:243:62: String literal expressions should be on the left side of an equalsIgnoreCase comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:264: @And should not be used. [RegexpSingleline]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:376:31: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:411:29: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:505:29: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:509:29: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:521: @And should not be used. [RegexpSingleline]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:759:45: '.' is followed by whitespace. [NoWhitespaceAfter]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:760:28: Unnecessary parentheses around lambda value. [UnnecessaryParentheses]
ui-tests/src/test/java/io/syndesis/qe/steps/
  CommonSteps.java:798: Empty catch block. [EmptyCatchBlock]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
I see I disabled the hook locally, now I am the first one to change commonSteps :D ok...

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert
Connection - CRUD | Create and delete | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu edit and view | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
@avano smoke tests are broken, api connector crud all passed

**Pull request merged**
