### PR TITLE
[FUSEQE-8568] Automation test for kafka TSL

### PR DESCRIPTION
**Pull request by Stefan365**
kafka security enhancement test
//test: `@db-to-kafka-to-db-secure`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by Stefan365** [comment]
hello world!

**Comment by Stefan365** [comment]
test

**Comment by Stefan365** [comment]
test

**Comment by Stefan365** [comment]
test x

**Comment by Stefan365** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
