### PR TITLE
[FUSEQE-8553] Disconnected install

### PR DESCRIPTION
**Pull request by avano**
//test: `@disconnected-install`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Disconnected install | Amazon DynamoDB 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Disconnected install | Amazon DynamoDB 
```

**Comment by avano** [comment]
@mkralik3 the one failure is related to the credentials PR

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@avano Please, create a backport to the master

**Pull request merged**
