### PR TITLE
[FUSEQE-7546] Remove OCP4HACKs

### PR DESCRIPTION
**Pull request by avano**
//test: `@integration-http-consumer-get or @integration-amq-irc or @simple-timer or @integrations-odata-read`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData Connector | Read entity collection from OData service tests 
OData Connector | Read single entity from OData service tests 
OData Connector | Read property of entity from OData service tests 
OData Connector | Read with expand query from OData service tests 
OData Connector | Read complex property from OData service tests 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
