### PR TITLE
[FUSEQE-5828] - Update Public API tests

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@publicapi and (not (@ENTESB-11653 or @ENTESB-11386))`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - environments point | Update tag in all integration 
Import and export integration test | Test export the all integrations and import it again 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
