### PR TITLE
simple timer action name renamed to just "simple"

### PR DESCRIPTION
**Pull request by jsafarik**
//test: `@gh-3856 or @gh-4466`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
@jsafarik you probably wanted gh `or` gh, because right now it tried to run a scenario that is annotated by both gh tags at the same time :grin:

**Comment by jsafarik** [comment]
@avano oh, ok, didn't know that :smile:

**Comment by jsafarik** [comment]
//test: `@gh-3856 or @gh-4466`

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by asmigala** [comment]
Already merged as part of #998, closing

**Pull request closed without merging**
