### PR TITLE
[ui][fix] fix data mapper card and action selection

### PR DESCRIPTION
**Pull request by mcada**
//test: `@db-connection-crud-1-read-update`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
@avano rdy to merge, failed tests are rest and the UI fail is about something else, I will look into it and fix in different PR as it has nothing to do with data mapper card and action

**Comment by avano** [comment]
@mkralik3 can you review, please? It is the same issue as you were mentioning yesterday

**Comment by mkralik3** [comment]
LGTM

**Pull request merged**
