### PR TITLE
[OData] Add OData v2 tests

### PR DESCRIPTION
**Pull request by jsafarik**
//test: `@odata-v2 or @odata-v4`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
utilities/src/main/java/io/syndesis/qe/resource/impl/
  WildFlyS2i.java:6:8: Unused import - io.syndesis.qe.utils.ODataUtils. [UnusedImports]
```

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData Connector | Read entity collection from OData service tests 
OData Connector | Read single entity from OData service tests 
OData Connector | Read property of entity from OData service tests 
OData Connector | Read with expand query from OData service tests 
OData Connector | Read complex property from OData service tests 
OData Connector | Create entity in OData service 
OData Connector | Delete entity in OData service 
OData Connector | Read wrong_datashape from OData service tests 
OData Connector | Read NPE from OData service tests 
OData Connector | Read string predicate without quotes from OData service tests 
OData Connector | Read entity w complex param from OData service tests 
OData Connector | Read enum mapping from OData service tests 
OData Connector | OData connector needs server certificate 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
OData V4 Connector | Read entity collection from OData service tests 
OData V4 Connector | Read single entity from OData service tests 
OData V4 Connector | Read property of entity from OData service tests 
OData V4 Connector | Read with expand query from OData service tests 
OData V4 Connector | Read complex property from OData service tests 
OData V4 Connector | Create entity in OData service 
OData V4 Connector | Delete entity in OData service 
OData V4 Connector | Read wrong_datashape from OData service tests 
OData V4 Connector | Read NPE from OData service tests 
OData V4 Connector | Read string predicate without quotes from OData service tests 
OData V4 Connector | Read entity w complex param from OData service tests 
OData V4 Connector | Read enum mapping from OData service tests 
OData V4 Connector | OData connector needs server certificate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
