### PR TITLE
[tw_sf] Fix - dropdown was reintroduced

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@support-page-download-specific-diagnostic or @integrations-twitter-to-salesforce`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Twitter to Salesforce | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Twitter to Salesforce | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  DataMapper.java:12:8: Unused import - org.apache.commons.validator.routines.EmailValidator. [UnusedImports]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@avano I know this was already approved, but I discovered why there was the sf-tw test failure, @mkralik3 can you please review and eventually provide some feedback?

**Comment by mkralik3** [comment]
LGTM

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
