### PR TITLE
[FUSEQE-2296] Fhir connector test

### PR DESCRIPTION
**Pull request by Stefan365**
//test: `@fhir`

lasting problems:
1. @fhir-2-patch, see TODO

2. Fhir Client connection unstability.
Client connection is extremely unstable. (see `FhirUtils.checkConnection()`, TODO)
and even renewed before each usage, it keeps failing on:
`ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to parse response from server when performing GET to URL http://localhost:8082/baseDstu3/Patient`

This problem seems to be related to our testsuite, (probably st. to do with `Given clean application state`) because if you run fhir-client in separate project, stability is OK.

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - FHIR - all actions | FHIR create operation 
Integration - FHIR - all actions | FHIR delete operation 
Integration - FHIR - all actions | FHIR patch operation 
Integration - FHIR - all actions | FHIR read operation 
Integration - FHIR - all actions | FHIR search operation 
Integration - FHIR - all actions | FHIR transaction operation 
Integration - FHIR - all actions | FHIR update operation 
```

**Comment by Stefan365** [comment]
test will fail anyway - as I pointed out in MR description.

**Comment by mkralik3** [comment]
I working on this PR right now. 
I have probably resolved the second problem. The FHIR pod was ready but in the pod logs, it looked that it was still starting. I extended `FHIR#isReady()` about checking the log whether the FHIR is really started.
```
    public boolean isReady() {
        return OpenShiftWaitUtils.isPodReady(OpenShiftUtils.getAnyPod(labelName, appName))
            && OpenShiftUtils.getPodLogs(appName).contains("Server:main: Started");
    }
```

**Comment by mkralik3** [comment]
There is an issue with the Patch operation, ENTESB-14237. As a workaround, the patch json can be set through data mapper.

**Comment by mkralik3** [comment]
Since I don't have permission to push changes to Stefan's repo, I merge this PR and create another one for changes.

**Pull request merged**
