### PR TITLE
google-sheets: fix pivot table test on firefox

### PR DESCRIPTION
**Pull request by mmelko**
also refactor scenario about copying big spreadsheet

//test: `@google-sheets`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmelko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
Google Sheets Connector | create spreadsheet 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmelko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB | Read and update operations 
Google Sheets Connector | create spreadsheet 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmelko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - DB to DB | Read and update operations 
Google Sheets Connector | create spreadsheet 
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
