### PR TITLE
[FUSEQE-5830] - updated salesforce UI tests

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@integrations-twitter-to-salesforce or @integrations-salesforce-to-db or @integration-kafka or @integration-sf-db or @integration-sf-producers or @integration-tw-sf`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce | AMQ to Fetch record with external id to AMQ 
Integration - Salesforce | AMQ to Create a new record to AMQ 
Integration - Salesforce | AMQ to Update record 
Integration - Salesforce | AMQ to Upsert record insert to AMQ 
Integration - Salesforce | AMQ to Upsert record update to AMQ 
Integration - Twitter | Mention to Salesforce create object 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - Salesforce to DB | Create 
Integration - Twitter to Salesforce | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce to DB | Create 
Integration - Twitter to Salesforce | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@mkralik3 what about those 2 failing tests?

**Comment by mkralik3** [comment]
@avano  ENTESB-11577 , however the fix doesn't resolve the problem with the tests. The dynamic waiting which test has is useless in that case because the form is there in the HTML document but the tests are too fast. In my POV, the 500ms timer should resolve the problem.

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce to DB | Create 
Integration - Twitter to Salesforce | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce to DB | Create 
Integration - Twitter to Salesforce | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce to DB | Create 
Integration - Twitter to Salesforce | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
