### PR TITLE
Set syndesis tag in the CR

### PR DESCRIPTION
**Pull request by asmigala**
//skip-ci

Needs [ENTESB-11274](https://issues.jboss.org/browse/ENTESB-11274) to work

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
Sorry, I accidentally ran all PRs on duplicated pipeline and aborted them, that's why it send message `Build finished. Tests FAILED`. You can ignore this last `syndesisqe` comment.

**Comment by asmigala** [comment]
No longer necessary

**Pull request closed without merging**
