### PR TITLE
[ui] Fix typo in mongo tests

### PR DESCRIPTION
**Pull request by asmigala**
//test: `@mongodb-update`

Didn't really have any effect, fixing just for consistency

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - DB to DB | Read and update operations 
MongoDB | MongoDB update 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
