### PR TITLE
[FUSEQE-6035] Apicurio test preliminar fix

### PR DESCRIPTION
**Pull request by Stefan365**
//test: `@apicurio-check-security-settings-oauth-2`

### CODE REVIEW

**Comment by Stefan365** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - OAuth 2  - known issue
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - OAuth 2  - known issue
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by Stefan365** [comment]
on local, @smoke passed, particular test: @apicurio-check-security-settings-oauth-2 is skipped.

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - OAuth 2  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - OAuth 2  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
