### PR TITLE
[ui][fix] Changed template to work on React UI 

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@template`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt 
Templates | Verify that the code editor for templates is working correctly 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt 
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
Those tests are going to work only on master because of syndesisio/syndesis#5955

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu edit and view 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt 
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Kebab menu 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt  - known issue
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Kebab menu 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt  - known issue
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
@mmuzikar please squash the commits to reflect the work done and I will merge the PR

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  Template.java:10: 'lombok.Getter' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  Template.java:13: Wrong order for 'org.openqa.selenium.By' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  Template.java:21: Wrong order for 'com.codeborne.selenide.Condition.visible' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  Template.java:21:1: Duplicate import to line 5 - com.codeborne.selenide.Condition.visible. [RedundantImport]
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  Template.java:22: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/
  Template.java:22:1: Duplicate import to line 3 - org.assertj.core.api.Assertions.assertThat. [RedundantImport]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt  - known issue
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
@mcada ^^ is squashed and ready to be merged

**Comment by mcada** [comment]
@avano or @asmigala  please check if the code is ok, this also requires manual merge

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt 
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Templates | Verify that the code editor for templates is working correctly  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
@asmigala If you can fit another code review in, could you take a look on this?

**Comment by avano** [comment]
@asmigala ^ once you have some time

**Pull request merged**
