### PR TITLE
[ui][fix] correctly fill todo host URL

### PR DESCRIPTION
**Pull request by mcada**
//test: `@integrations-webhook-api-connector or @integrations-api-connector`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Webhook to API connector | Test to reproduce #3727 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Webhook to API connector | Test to reproduce #3727 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
@asmigala can we please merge this PR as the issue why the test is failing is different from this PR?

**Pull request merged**
