### PR TITLE
[FUSEQE-7785] Fixing FTP server, timeout

### PR DESCRIPTION
**Pull request by Stefan365**
//test: `@integrations-ftp-to-ftp`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
utilities/src/main/java/io/syndesis/qe/utils/
  FtpUtils.java:48: 'try' child has incorrect indentation level 14, expected level should be 12. [Indentation]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
