### PR TITLE
[UI] only automatically open unnamed collections on data mapper

### PR DESCRIPTION
**Pull request by wyvie**
we don't want to open all collections automatically - only unnamed ones
if we automatically open all collections, there might be field names collision

on the contrary, if we want to open *all* collections, there is distinct
step for that

//test: `@data-buckets-check-popups or @email-receive or @gmail-receive or @integrations-twitter-to-db`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mcada** [comment]
@wyvie can you please add annotation for a test which is fixed by this PR?

**Comment by wyvie** [comment]
//test: `@integrations-data-buckets or @email-receive or @gmail-receive or @integrations-twitter-to-db`

**Comment by mcada** [comment]
To clarify our requirement: what we want to see is a mapping with unnamed collection inside data mapper which is not on position 1. If it is in your fhir test, please do a draft PR.

**Comment by wyvie** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
