### PR TITLE
[FUSEQE-6004] Fix salesforce - db test

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@integrations-salesforce-to-database-scenario`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - Salesforce to DB | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce to DB | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce to DB | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Salesforce to DB | Create 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@mkralik3 is this surpassed by this? https://github.com/syndesisio/syndesis-qe/pull/1086/files

**Comment by mkralik3** [comment]
@tplevko correct ;)

**Comment by tplevko** [comment]
OK, closing

**Pull request closed without merging**
