### PR TITLE
[relates #310] Ftp rest, validation

### PR DESCRIPTION
**Pull request by Stefan365**
FTP rest test, adding validation, part 1.

### CODE REVIEW

**Comment by dsimansk** [comment]
@Stefan365 could you pls just add the required dependency without pom reformat? Sorry about that reoccurring issue.

**Comment by Stefan365** [comment]
@dsimansk done (utilities/pom.xml)

**Comment by dsimansk** [comment]
@Stefan365 now the pom is completely gone from commit with common-net depedency also.

**Comment by Stefan365** [comment]
@dsimansk sorry.

**Comment by Stefan365** [comment]
@dsimansk done

**Pull request merged**
