### PR TITLE
[rest] - Test for new endpoint was added

### PR DESCRIPTION
**Pull request by mkralik3**
* Test for a new endpoint for creating unassigned tag was added
  * Update test, now the unassigned tag is not removed from the syndesis
  * Add test for usage of tags

//test: `@publicapi`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert
Connection - CRUD | Credentials | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Create and delete | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu edit and view
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Credentials | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Create and delete | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu edit and view
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Credentials | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Create and delete | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu | <font color="red"><b>FAILED</b></font> | mcada@redhat.com
Connection - CRUD | Kebab menu edit and view
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by mkralik3** [comment]
I added also a test for a number of usages of the tag.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
C | o
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
