### PR TITLE
WIP: odata connector smoke tests

### PR DESCRIPTION
**Pull request by jsafarik**
Until there is sample OData service, those are just for manual testing.

### CODE REVIEW

**Comment by jsafarik** [comment]
//skip-ci

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by phantomjinx** [comment]
@jsafarik
You can setup a sample odata server using the [ODataTestServer](https://github.com/syndesisio/syndesis/blob/master/app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataTestServer.java) class. It has a main method so you can export from eclipse and run as a jar.

**Comment by jsafarik** [comment]
@phantomjinx 
Thanks for the advice, I was just trying to get it running. I ended up moving the classes needed for it to run to a new project and was able to start it, but when I try to access localhost:<port>/odata4/Products.svc/ it says that localhost redirected me too many times. With this page not accessible I cannot validate it in syndesis. Have any idea what can be causing this?

**Comment by phantomjinx** [comment]
@jsafarik 
Yeah. So the server is not perfect and doesn't redirect automatically (created from the tutorials). However, if you go to ../Products.svc/$metadata then you should see the metadata and navigating to any particular links, eg. .../Products.svc/Products(1), you should see the data. Only 3 products in there at this stage but easy to add more and we can extend as much as needed.

**Comment by avano** [comment]
@jsafarik I assume this is a work in progress, am I right? if so, please change the title to `WIP: ...` until it's done

**Comment by jsafarik** [comment]
@avano yes, it is (right now it is meant only for manual testing, soon it will be automated). Changed the title, thanks for the reminder.

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request closed without merging**
