### PR TITLE
[FUSEQE-5982] Fix @slack-to-db test

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@slack-to-db`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
@tplevko also fixed as part of https://github.com/syndesisio/syndesis-qe/pull/1077 :) 
In my POV, there should be a dropdown chooser instead of directly fill-in an input (what if the channel doesn't exist). The Syndesis UI should not allow the user filling in the channel name but only allows the user choosing from an existing channels. I have to create a JIRA issue for that.

**Comment by tplevko** [comment]
@mkralik3 sure, this sounds like a reasonable requirement. 

Closing this as it's fixed in different PR.

**Pull request closed without merging**
