### PR TITLE
[FUSEQE-1450] Add HTTPS connector tests

### PR DESCRIPTION
**Pull request by avano**
//test: `@integration-http`

### CODE REVIEW

**Comment by avano** [comment]
needs a new daily build

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - HTTP | HTTP GET to AMQ 
Integration - HTTP | HTTPS GET to AMQ 
Integration - HTTP | HTTP POST to AMQ 
Integration - HTTP | HTTPS POST to AMQ 
Integration - HTTP | HTTP PUT to AMQ 
Integration - HTTP | HTTPS PUT to AMQ 
Integration - HTTP | HTTP DELETE to AMQ 
Integration - HTTP | HTTPS DELETE to AMQ 
Integration - HTTP | HTTP PATCH to AMQ 
Integration - HTTP | HTTPS PATCH to AMQ 
Integration - HTTP | HTTP OPTIONS to AMQ 
Integration - HTTP | HTTPS OPTIONS to AMQ 
Integration - HTTP | HTTP TRACE to AMQ 
Integration - HTTP | HTTPS TRACE to AMQ 
Integration - HTTP | HTTP HEAD to AMQ 
Integration - HTTP | HTTPS HEAD to AMQ 
Integration - HTTP | HTTP Response Datamapper 
Integration - HTTP | HTTPS Response Datamapper 
Integration - HTTP | AMQ to GET 
Integration - HTTP | AMQ to GET 
Integration - HTTP | AMQ to POST 
Integration - HTTP | AMQ to POST 
Integration - HTTP | AMQ to PUT 
Integration - HTTP | AMQ to PUT 
Integration - HTTP | AMQ to DELETE 
Integration - HTTP | AMQ to DELETE 
Integration - HTTP | AMQ to PATCH 
Integration - HTTP | AMQ to PATCH 
Integration - HTTP | AMQ to OPTIONS 
Integration - HTTP | AMQ to OPTIONS 
Integration - HTTP | AMQ to TRACE 
Integration - HTTP | AMQ to TRACE 
Integration - HTTP | AMQ to HEAD 
Integration - HTTP | AMQ to HEAD 
Integration - HTTP | HTTP to SQL with split 
Integration - HTTP | HTTPS to SQL with split 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
