### PR TITLE
[ui][sql] Add tests for SQL predicates (gh-5016)

### PR DESCRIPTION
**Pull request by asmigala**
//test: `@gh-5016`

### CODE REVIEW

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
The four failures are expected (see syndesisio/syndesis#5016 )

**Pull request merged**
