### PR TITLE
google-sheets fix tests to work with react ui

### PR DESCRIPTION
**Pull request by mmelko**
also fixes rest soak test test
//test: `@google-sheets`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  GoogleSheetsSteps.java:5: Wrong order for 'io.syndesis.qe.pages.SyndesisRootPage' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  GoogleSheetsSteps.java:8: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  GoogleSheetsSteps.java:9: Wrong order for 'org.springframework.beans.factory.annotation.Autowired' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  GoogleSheetsSteps.java:5: Wrong order for 'io.syndesis.qe.pages.SyndesisRootPage' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  GoogleSheetsSteps.java:8: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/other/
  GoogleSheetsSteps.java:9: Wrong order for 'org.springframework.beans.factory.annotation.Autowired' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmelko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Google Sheets Connector | Append messages from DB 
Google Sheets Connector | Update messages from DB - Rows 
Google Sheets Connector | Update messages from DB - Columns 
Google Sheets Connector | create pivottable from sample data 
Google Sheets Connector | Update title 
Google Sheets Connector | get properties of sheet 
Google Sheets Connector | add chart 
Google Sheets Connector | Copy big spreadsheet 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmelko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Validate all credentials 
Google Sheets Connector | Copy Big SS to DB and back using split/aggregate 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
