### PR TITLE
[Upgrade] Sort tags before selecting the latest one

### PR DESCRIPTION
**Pull request by avano**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
@avano   Are two more commits in this PR (in comparison to PR #1484 ) related only for master? If not, please, backport them to 1.10.x too.

**Comment by avano** [comment]
@mkralik3 yes they are

**Pull request merged**
