### PR TITLE
[ui][new] extend log connector tests

### PR DESCRIPTION
**Pull request by mcada**
//test: `@integrations-log`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
@avano one integration did not start in time, the tests are ok

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
