### PR TITLE
[update-selenide] Update selenide in order to be able to use chrome 79

### PR DESCRIPTION
**Pull request by jsafarik**

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/
  Todo.java:7: Wrong order for 'org.openqa.selenium.By' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/
  Todo.java:9: Wrong order for 'com.codeborne.selenide.Selenide.$' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/
  Todo.java:11: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/
  ReviewEditConnectorDetails.java:11: Wrong order for 'io.syndesis.qe.pages.SyndesisPageObject' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/
  ReviewEditConnectorDetails.java:12: Wrong order for 'io.syndesis.qe.logic.common.wizard.WizardPhase' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/
  UploadSwaggerSpecification.java:4: Wrong order for 'io.syndesis.qe.fragments.common.form.ApiSpecificationForm' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/
  UploadSwaggerSpecification.java:7: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/
  UploadSwaggerSpecification.java:8: Wrong order for 'org.openqa.selenium.By' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/
  UploadSwaggerSpecification.java:10: Wrong order for 'com.codeborne.selenide.Condition.exist' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
