### PR TITLE
[ui][update] move test timeout from java to test.properties

### PR DESCRIPTION
**Pull request by mcada**
Please do not push sooner than on Monday 25 as I want nightly builds this week to run with longer delay.

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
