### PR TITLE
[FUSEQE-5863] Add Jira issue hooks

### PR DESCRIPTION
**Pull request by tplevko**
//skip-ci

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by tplevko** [comment]
Agree it will make more sense to have the hook in separate class - I refactored the code, please review.

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@asmigala can you please have another look?

**Comment by tplevko** [comment]
@asmigala maybe now?

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by tplevko** [comment]
@asmigala - updated again

**Comment by tplevko** [comment]
@asmigala sure, totally forgot about it. Thanks for reminder, I added some info to the README

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
