### PR TITLE
[ui][new-test] added webhook integration tests

### PR DESCRIPTION
**Pull request by jstastny-cz**
//test: `@webhook`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jstastny-cz** [comment]
The results are expected (unfortunately). Need to move to different feature file, I didn't notice the feature name 'Feature: Integration - DB to API'

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by jstastny-cz** [comment]
Failure of "@webhook Feature: Webhook extension " is not expected.

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
