### PR TITLE
[AMQ] Use label for syndesis-amq to be selectable by broker-amq-tcp svc

### PR DESCRIPTION
**Pull request by avano**
//test: `@integrations-amq-to-rest`

### CODE REVIEW

**Comment by avano** [comment]
@mkralik3 try with this one

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
I added the test and run it again ;) it should be passed now.

**Comment by mkralik3** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Pull request merged**
