### PR TITLE
[ui][fix] fix concur oauth validation

### PR DESCRIPTION
**Pull request by mcada**
//test: @concur-listitem-create-delete

### CODE REVIEW

**Comment by mcada** [comment]
retest this please

**Comment by mcada** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mcada** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
