### PR TITLE
[rest][improvement] - decreased time (on half) of execution @PublicApi

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@rest and (@publicapi and (not @gh-6360))`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - integrations point | Export and import integrations according to tag 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
Needs to update one test because this issue was resolved: https://github.com/syndesisio/syndesis/issues/5917

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - integrations point | Export and import integrations according to tag 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
One rest test failed due to https://github.com/syndesisio/syndesis/issues/6360 
UI tests failed due to invalid selector in the Connection page. The fix should be here: https://github.com/syndesisio/syndesis-qe/pull/1057

**Comment by mkralik3** [comment]
skip verification UI `cicddialog.feature` due to https://github.com/syndesisio/syndesis/issues/6362

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - environments point | Update tag in all integration 
Public API - integrations point | Deploy and redeploy integration 
Public API - integrations point | Export and import all integrations from Syndesis according to tag 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
retest this please

Please ignore the upcoming test results. I want to see results for the whole rest suite on the Jenkins with these changes before merging.

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - HTTP | POST to AMQ 
Integration - HTTP | PUT to AMQ 
Integration - HTTP | DELETE to AMQ 
Integration - HTTP | PATCH to AMQ 
Integration - HTTP | OPTIONS to AMQ 
Integration - HTTP | TRACE to AMQ 
Integration - HTTP | HEAD to AMQ 
Integration - HTTP | HTTP Response Datamapper 
Integration - HTTP | AMQ to GET 
Integration - HTTP | AMQ to POST 
Integration - HTTP | AMQ to PUT 
Integration - HTTP | AMQ to DELETE 
Integration - HTTP | AMQ to PATCH 
Integration - HTTP | AMQ to OPTIONS 
Integration - HTTP | AMQ to TRACE 
Integration - HTTP | AMQ to HEAD 
Integration - HTTP | HTTP to SQL with split 
Integration - Kafka | SalesForce to Kafka to AMQ 
Integration - Monitoring | Metrics and activity log 
Integration - S3 | S3 to S3 - Create 
Integration - S3 | S3 to S3 - Delete All 
Integration - S3 | S3 to S3 - Delete All Prefixed 
Integration - S3 | S3 to S3 - Delete Filtered 
Integration - Salesforce | On create to DB 
Integration - Salesforce | On delete to DB 
Integration - Salesforce | On update to DB 
Integration - Salesforce | AMQ to Delete record 
Integration - Salesforce | AMQ to Delete record with external id 
Integration - Salesforce | AMQ to Fetch record to AMQ 
Integration - Salesforce | AMQ to Fetch record with external id to AMQ 
Integration - Salesforce | AMQ to Create a new record to AMQ 
Integration - Salesforce | AMQ to Update record 
Integration - Salesforce | AMQ to Upsert record insert to AMQ 
Integration - Salesforce | AMQ to Upsert record update to AMQ 
Integration - SNS | DB to SNS syndesis-out 
Integration - SNS | DB to SNS arn:syndesis-out 
Integration - SQS | SQS to SQS ARN 
Integration - SQS | SQS to SQS delete after read 
Integration - SQS | SQS to AMQ don't delete after read 
Integration - SQS | SQS to AMQ delete when filtered out 
Integration - SQS | SQS to AMQ don't delete when filtered out 
Integration - SQS | SQS to SQS Max objects to poll 
Integration - SQS | SQS to AMQ poll delay 
Integration - SQS | AMQ to SQS send delay 
Integration - SQS | SQS FIFO to AMQ 
Integration - SQS | HTTP to SQS Batch 
Integration - SQS | DB to SQS FIFO ExchangeID deduplication 
Integration - SQS | DB to SQS FIFO ContentBased deduplication 
Integration - SQS | DB to SQS FIFO Constant group id 
Integration - SQS | DB to SQS FIFO property value group id 
Integration - Twitter | Mention to Salesforce create object 
Integration - IRC | AMQ to Send message 
Integration - IRC | Private message to FTP 
Public API - connections point | Change connection properties 
Public API - environments point | Get all tags from Syndesis 
Public API - environments point | Get all tags with the number of usages 
Public API - environments point | Get all tags from Syndesis without duplicates 
Public API - environments point | Add new tag to the Syndesis 
Public API - environments point | Update tag in all integration 
Public API - environments point | Delete tag from all integrations 
Public API - integrations point | Add and get tags in integration 
Public API - integrations point | Update tags on integration without remove previous 
Public API - integrations point | Update tags on integration uncheck previous 
Public API - integrations point | Delete tag from integration 
Public API - integrations point | Stop integration 
Public API - integrations point | Deploy and redeploy integration 
Public API - integrations point | Export and import integrations according to tag  - known issue
Public API - integrations point | Export and import all integrations from Syndesis according to tag 
Integration - Timer | Simple Timer to GET 
Integration - Timer | Cron Timer to GET 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Kafka | SalesForce to Kafka to AMQ 
Integration - Monitoring | Metrics and activity log 
Integration - S3 | S3 to S3 - Create 
Integration - S3 | S3 to S3 - Delete All 
Integration - S3 | S3 to S3 - Delete All Prefixed 
Integration - S3 | S3 to S3 - Delete Filtered 
Integration - Salesforce | On create to DB 
Integration - Salesforce | On delete to DB 
Integration - Salesforce | On update to DB 
Integration - Salesforce | AMQ to Delete record 
Integration - Salesforce | AMQ to Delete record with external id 
Integration - Salesforce | AMQ to Fetch record to AMQ 
Integration - Salesforce | AMQ to Fetch record with external id to AMQ 
Integration - Salesforce | AMQ to Create a new record to AMQ 
Integration - Salesforce | AMQ to Update record 
Integration - Salesforce | AMQ to Upsert record insert to AMQ 
Integration - Salesforce | AMQ to Upsert record update to AMQ 
Integration - SNS | DB to SNS syndesis-out 
Integration - SNS | DB to SNS arn:syndesis-out 
Integration - SQS | SQS to SQS ARN 
Integration - SQS | SQS to SQS delete after read 
Integration - SQS | SQS to AMQ don't delete after read 
Integration - SQS | SQS to AMQ delete when filtered out 
Integration - SQS | SQS to AMQ don't delete when filtered out 
Integration - SQS | SQS to SQS Max objects to poll 
Integration - SQS | SQS to AMQ poll delay 
Integration - SQS | AMQ to SQS send delay 
Integration - SQS | SQS FIFO to AMQ 
Integration - SQS | HTTP to SQS Batch 
Integration - SQS | DB to SQS FIFO ExchangeID deduplication 
Integration - SQS | DB to SQS FIFO ContentBased deduplication 
Integration - SQS | DB to SQS FIFO Constant group id 
Integration - SQS | DB to SQS FIFO property value group id 
Integration - Twitter | Mention to Salesforce create object 
Integration - IRC | AMQ to Send message 
Integration - IRC | Private message to FTP 
Public API - connections point | Change connection properties 
Public API - environments point | Get all tags from Syndesis 
Public API - environments point | Get all tags with the number of usages 
Public API - environments point | Get all tags from Syndesis without duplicates 
Public API - environments point | Add new tag to the Syndesis 
Public API - environments point | Update tag in all integration 
Public API - environments point | Delete tag from all integrations 
Public API - integrations point | Add and get tags in integration 
Public API - integrations point | Update tags on integration without remove previous 
Public API - integrations point | Update tags on integration uncheck previous 
Public API - integrations point | Delete tag from integration 
Public API - integrations point | Stop integration 
Public API - integrations point | Deploy and redeploy integration 
Public API - integrations point | Export and import integrations according to tag  - known issue
Public API - integrations point | Export and import all integrations from Syndesis according to tag 
Integration - Timer | Simple Timer to GET 
Integration - Timer | Cron Timer to GET 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - environments point | Get all tags from Syndesis without duplicates 
Public API - environments point | Add new tag to the Syndesis 
Public API - environments point | Update tag in all integration 
Public API - environments point | Delete tag from all integrations 
Public API - integrations point | Add and get tags in integration 
Public API - integrations point | Update tags on integration without remove previous 
Public API - integrations point | Update tags on integration uncheck previous 
Public API - integrations point | Delete tag from integration 
Public API - integrations point | Stop integration 
Public API - integrations point | Deploy and redeploy integration 
Public API - integrations point | Export and import all integrations from Syndesis according to tag 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Pull request merged**
