### PR TITLE
Change url for petstore swagger

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@create-api-connector-from-url-test or @api-client-auth-api-key-query or @api-client-auth-api-key-headers`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | API key used in API client provided in headers 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Testing authentication options of API client | API key used in API client provided in query 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by mkralik3** [comment]
Backports for https://github.com/syndesisio/syndesis-qe/pull/1576

**Pull request merged**
