### PR TITLE
[rest][1.7.x] - PublicOauth template fixes

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci
A backport of this PR https://github.com/syndesisio/syndesis-qe/pull/1053

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
@mkralik3 please fix the conflict so that it can be merged

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
Sorry, I accidentally ran all PRs on duplicated pipeline and aborted them, that's why it send message `Build finished. Tests FAILED`. You can ignore this last `syndesisqe` comment.

**Comment by avano** [comment]
@mkralik3 please fix the conflict

**Pull request merged**
