### PR TITLE
[fix] don't crash on non-existing label

### PR DESCRIPTION
**Pull request by mmuzikar**
//test: `@api-provider-simple-response-type`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | API Provider operation with simple return type 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
API Provider Integration | API Provider operation with simple return type 
Integration - DB to DB | Read and update operations 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
The integration didn't get to running state, but it passed the step I wanted it to pass.

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by jsafarik** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
