### PR TITLE
Fixes after UI changes

### PR DESCRIPTION
**Pull request by mkralik3**
* Choose step was fixed
* Add a Step button was fixed
* Publish button was fixed
* Log step for middle step was hardcoded. (instead of connection Log)

//test: `@ui`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
@mkralik3 I forgot to say that there is a blocker opened - https://github.com/syndesisio/syndesis/issues/4308 

after some of the tests (amq-to-rest was the first one where I encountered that) the reset db is blocked and it never completes :/ and the same happened in your PR job, so I killed it

**Pull request merged**
