### PR TITLE
Selector utils

### PR DESCRIPTION
**Pull request by mmuzikar**
/test: `@ui`

### CODE REVIEW

**Comment by mmuzikar** [comment]
retest this please

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/
  RowList.java:21: Line has trailing spaces. [RegexpSingleline]
ui-tests/src/test/java/io/syndesis/qe/pages/login/
  GitHubLogin.java:7: Wrong order for 'io.syndesis.qe.utils.ByUtils' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/utils/
  ByUtils.java:50:49: Unnecessary parentheses around lambda value. [UnnecessaryParentheses]
ui-tests/src/test/java/io/syndesis/qe/utils/
  ByUtils.java:64:39: Unnecessary parentheses around lambda value. [UnnecessaryParentheses]
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/utils/
  ByUtils.java:59: Line has trailing spaces. [RegexpSingleline]
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Pull request closed without merging**
