### PR TITLE
Make _really_ sure nexus is used

### PR DESCRIPTION
**Pull request by asmigala**
//test: `@integrations-amq-to-rest-xml-message`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by avano** [comment]
lets :pray:

**Comment by asmigala** [comment]
> lets pray

I mean, the tests passed but those were run with upstream _and_ had syndesis predeployed, so the changed code didn't even run. Works on my machine :tm: though.

**Comment by avano** [comment]
I tried on AWS and it seemed to work

**Pull request merged**
