### PR TITLE
Apicurito fixes rebase

### PR DESCRIPTION
**Pull request by asmigala**
//test: `@apicurio`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:6: 'cucumber.api.java.en.Then' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:8: Wrong order for 'io.syndesis.qe.utils.TestUtils' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:10: 'lombok.extern.slf4j.Slf4j' should be separated from previous imports. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:11: Wrong order for 'org.openqa.selenium.By' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:15: Wrong order for 'com.codeborne.selenide.CollectionCondition.sizeGreaterThanOrEqual' import. [ImportOrder]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:16: Using the '.*' form of import should be avoided - com.codeborne.selenide.Condition.*. [AvoidStarImport]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:17: Using the '.*' form of import should be avoided - com.codeborne.selenide.Selenide.*. [AvoidStarImport]
ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/
  ApicurioSteps.java:18: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Customization - API Connector - ApicurIO GUI | Check if operations change with an error is propagated into connector review page from ApicurIO GUI 
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - no security  - known issue
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - basic security  - known issue
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - API key  - known issue
Customization - API Connector - ApicurIO GUI | Check apicurio security settings - OAuth 2  - known issue
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by asmigala** [comment]
@mcada all the failures are due to open issues or issues not yet in any build. Please merge

**Pull request merged**
