### PR TITLE
[fix-lifecycle] Fix integration lifecycle tests

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@integrations-lifecycle`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Lifecycle | Create with same name 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@avano the 1 failed test is supposed to be failing

**Pull request merged**
