### PR TITLE
Kafka tests refactor + add test for Managed Kafka

### PR DESCRIPTION
**Pull request by mkralik3**
//skip-ci (due to AtlasMap issue)

- Refactored Kafka tests into one test scenario with Scenario Outline
- Add (semi-auto) test scenario for Managed Kafka (PLAIN and OAUTHBEARER)

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Review by avano — APPROVED** [review]

**Pull request merged**
