### PR TITLE
[FUSEQE-1450] Add HTTPS connector tests

### PR DESCRIPTION
**Pull request by avano**
//test: `@integration-http`

### CODE REVIEW

**Comment by avano** [comment]
needs a new daily build

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - HTTP | HTTPS to SQL with split 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - HTTP | HTTPS GET to AMQ 
Integration - HTTP | HTTPS POST to AMQ 
Integration - HTTP | HTTPS PUT to AMQ 
Integration - HTTP | HTTPS DELETE to AMQ 
Integration - HTTP | HTTPS PATCH to AMQ 
Integration - HTTP | HTTPS OPTIONS to AMQ 
Integration - HTTP | HTTPS TRACE to AMQ 
Integration - HTTP | HTTPS HEAD to AMQ 
Integration - HTTP | HTTP Response Datamapper 
Integration - HTTP | HTTPS Response Datamapper 
Integration - HTTP | HTTP to SQL with split 
Integration - HTTP | HTTPS to SQL with split 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
```

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - HTTP | HTTPS GET to AMQ 
Integration - HTTP | HTTPS POST to AMQ 
Integration - HTTP | HTTPS PUT to AMQ 
Integration - HTTP | HTTPS DELETE to AMQ 
Integration - HTTP | HTTPS PATCH to AMQ 
Integration - HTTP | HTTPS OPTIONS to AMQ 
Integration - HTTP | HTTPS TRACE to AMQ 
Integration - HTTP | HTTPS HEAD to AMQ 
Integration - HTTP | HTTPS Response Datamapper 
Integration - HTTP | HTTPS to SQL with split 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - HTTP | AMQ to GET 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - HTTP | HTTPS Response Datamapper 
```

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
