### PR TITLE
[FUSEQE-6054] Remove hardcoded gmail address from tests

### PR DESCRIPTION
**Pull request by tplevko**
//test: `@oauth-gmail or @data-buckets-usage or @template-code-editor or @db-template-mustache-file-upload or @db-template-send or @gmail-send or @gmail-receive or @email-send`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Checkstyle verification failed with:
```
utilities/src/main/java/io/syndesis/qe/utils/
  GMailUtils.java:12: Wrong order for 'javax.mail.MessagingException' import. [ImportOrder]
utilities/src/main/java/io/syndesis/qe/utils/
  GMailUtils.java:25: Wrong order for 'org.assertj.core.api.Assertions.fail' import. [ImportOrder]
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connections - OAuth | Testing Gmail OAuth connector 
Email connector | Send an e-mail 
Email connector | Send an e-mail 
Templates | Verify that the code editor for templates is working correctly 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Email connector | Send an e-mail 
Email connector | Send an e-mail 
Templates | Verify that the code editor for templates is working correctly 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Connections - OAuth | Testing Gmail OAuth connector 
Integration - Databucket | Create 
Integration - DB to DB | Read and update operations 
Email connector | Send an e-mail 
Email connector | Send an e-mail 
Google mail Connector | Send an e-mail 
Google mail Connector | Receive an e-mail 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt 
Templates | Verify that the code editor for templates is working correctly 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Validate all credentials 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Connections - OAuth | Testing Gmail OAuth connector 
Integration - Databucket | Create 
Integration - DB to DB | Read and update operations 
Email connector | Send an e-mail 
Email connector | Send an e-mail 
Google mail Connector | Send an e-mail 
Google mail Connector | Receive an e-mail 
Templates | Send an Email with text formatted by Mustache template 
Templates | Send an Email with text formatted by Freemarker template 
Templates | Send an Email with text formatted by Velocity template 
Templates | Send an Email with text formatted by Mustache template uploaded from resources/templates/mustache.txt 
Templates | Verify that the code editor for templates is working correctly 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connections - OAuth | Testing Gmail OAuth connector 
Templates | Verify that the code editor for templates is working correctly 
```

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
@avano the tests which failed are not yet fixed, so they were supposed to fail:
```
Connections - OAuth | Testing Gmail OAuth connector 
Templates | Verify that the code editor for templates is working correctly 
```

**Pull request merged**
