### PR TITLE
[FUSEQE-8633] Extend PublicApi rest tests

### PR DESCRIPTION
**Pull request by mkralik3**
* Reproducers for ENTESB-12885 and ENTESB-13013
* Added test for checking whether a connection was created after the import
* Added test for deploying integration after import

//test: `@ENTESB-13013 or @ENTESB-12885 or @export-import-and-deploy or @export-import-integrations-with-connection-test or @deploy-redeploy-integration`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Public API - connections point | Change connection properties for integration 
```

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
```

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
