### PR TITLE
[FUSEQE-10646] Move images to quay

### PR DESCRIPTION
**Pull request by mkralik3**
//test: `@integration-irc-ftp or @fhir-0-create or @simple-timer or @integrations-kudu-insert or @integrations-db-to-db-mysql or @sftp-download-sftp-upload or @mongodb-insert`

### CODE REVIEW

**Comment by mkralik3** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Integration - IRC | Private message to FTP 
Integration - DB to DB | Read and update operations 
Kudu connector | Insert data into kudu table 
MongoDB | MongoDB insert and consume tail 
Integration - SFTP to SFTP | Download and upload data to sftp 
```

**Comment by avano** [comment]
retest this please

**Comment by syndesisqe** [comment]
Following scenarios failed:
```
Integration - DB to DB mysql | Read and create operations on mysql 
Integration - DB to DB | Read and update operations 
Integration - FHIR - all actions | FHIR create operation 
Kudu connector | Insert data into kudu table 
MongoDB | MongoDB insert and consume tail 
Integration - SFTP to SFTP | Download and upload data to sftp 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

**Pull request merged**
