### PR TITLE
[ui-tests] Fix data-bucket tests

### PR DESCRIPTION
**Pull request by mastepan**
//test: `@integrations-data-buckets`

### CODE REVIEW

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests FAILED

**Comment by tplevko** [comment]
retest this please

**Comment by syndesisqe** [comment]
Build finished. Tests PASSED

**Pull request merged**
